### ISSUE TITLE
Failure in `npm run dev`

### ISSUE THREAD

**Issue by adoyle-h** [luin/medis#10]
![image](https://cloud.githubusercontent.com/assets/1998490/12315373/24f8465e-bab5-11e5-82ab-eabcbba1af20.png)

node version: v0.12.9
npm version: 3.5.3

**Comment by luin** [comment]
Hi, this should be fixed in the master branch yesterday. The "Config.scss" is in the repo: https://github.com/luin/medis/blob/master/client/components/main/Main/Database/Content/Config.scss. Would you clone the repo and try again?

**Comment by adoyle-h** [comment]
@luin I cloned the master branch of repo just two hours ago. And current local git HEAD points to 6183d2d commit.

**Comment by bripkens** [comment]
Running into the same issue. @luin: The error message references a different `Config.scss`: `client/components/main/Main/ConnectionSelector/Config.scss`.

Required by: https://github.com/luin/medis/blob/6183d2d0d9e4bab597e803c80a8d1e2b01ab8abb/client/components/main/Main/ConnectionSelector/Config.jsx#L10

**Comment by luin** [comment]
That's strange. Does the Config.scss exist in that folder? If not, rename config.scss to Config.scss may fix the problem.

**Comment by adoyle-h** [comment]
![image](https://cloud.githubusercontent.com/assets/1998490/12321841/56709b92-baeb-11e5-9d53-acf2a1a671a8.png)

**Comment by pgrippi** [comment]
I'm getting the same error when running `npm run deploy` (master is 6183d2d0d9e4bab597e803c80a8d1e2b01ab8abb):

```
[pgrippi ~/Sources/medis] [master] ❯ npm run deploy

> medis@0.2.0 deploy /Users/pgrippi/Sources/medis
> NODE_ENV=production ./bin/deploy

Hash: 67f77d24f17949dc6011
Version: webpack 1.12.11
Time: 35137ms
    + 386 hidden modules

ERROR in ./client/components/main/Main/ConnectionSelector/Config.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ./Config.scss in /Users/pgrippi/Sources/medis/client/components/main/Main/ConnectionSelector
 @ ./client/components/main/Main/ConnectionSelector/Config.jsx 41:0-24
mv: rename main.js to deploy/main.js: No such file or directory
mv: rename pattern-manager.js to deploy/pattern-manager.js: No such file or directory
```

As with @adoyle-h above, the Config.scss file doesn't exist:

```
[pgrippi ~/Sources/medis] [master] ❯ ls client/components/main/Main/ConnectionSelector
Config.jsx   Favorite.jsx index.jsx
```

But it does exist in `client/components/main/Main/Database/Content`

```
[pgrippi ~/Sources/medis] [master] ❯ ll client/components/main/Main/Database/Content/ 
total 88
drwxr-xr-x  11 pgrippi  staff    374 Jan 13 19:01 .
drwxr-xr-x   6 pgrippi  staff    204 Jan 13 19:01 ..
-rw-r--r--   1 pgrippi  staff  12288 Jan 13 19:01 Config.jsx
-rw-r--r--   1 pgrippi  staff    215 Jan 13 19:01 Config.scss
-rw-r--r--   1 pgrippi  staff   2148 Jan 13 19:01 Footer.jsx
drwxr-xr-x  14 pgrippi  staff    476 Jan 13 19:01 KeyContent
-rw-r--r--   1 pgrippi  staff   1144 Jan 13 19:01 TabBar.jsx
-rw-r--r--   1 pgrippi  staff    225 Jan 13 19:01 TabBar.scss
-rw-r--r--   1 pgrippi  staff   5768 Jan 13 19:01 Terminal.jsx
-rw-r--r--   1 pgrippi  staff    802 Jan 13 19:01 Terminal.scss
-rw-r--r--   1 pgrippi  staff   2322 Jan 13 19:01 index.jsx
```

**Comment by luin** [comment]
Sorry for the delay! I'm just back from vacation. The Config.scss is removed incautiously by me in the latest commit. :cry:
