### ISSUE TITLE
Medis.app launched with no interface

### ISSUE THREAD

**Issue by lyqeyes** [luin/medis#101]
system:  MBP,  OS X EI Capitan version 10.11.6 (15G31) 

I download zip package from github and run deploy commands  following the README.md
> npm install
> npm run deploy

then the Medis.app generated successfully.  
But when I run it, there is only an icon in docker with no User Interface. 

![image](https://user-images.githubusercontent.com/9962597/30426686-8123e2e4-997f-11e7-84c7-a21ebb89de33.png)

What's the problem?  
Who can help me...

![image](https://user-images.githubusercontent.com/9962597/30426712-9f84a55c-997f-11e7-9469-8d509e2fb47b.png)

**Comment by srarcbrsent** [comment]
i got the same problem

**Comment by raulferras** [comment]
Same here, I'm on macOS Sierra

**Comment by keenen** [comment]
I too had the same issue.

**Comment by motiejunas** [comment]
For me too...

**Comment by joshuatalb** [comment]
I'm also bumping into this issue. I'm running MacOS High Sierra too. The only way I could get it to work is by running `npm run dev`, and then running `npm run start` (in another tab) after Webpack had finished building. This brings up the UI and allows you to start using it. Not ideal, but it's a workaround at least.

**Comment by pingcheng** [comment]
same here and also 
`[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0`
this error msg

**Comment by RaMin0** [comment]
+1

**Comment by fortis** [comment]
+1

**Comment by vladlavrik** [comment]
+1

**Comment by romikzo** [comment]
+1

**Comment by wakaryry** [comment]
+1

**Comment by Enoooch** [comment]
+1

**Comment by daniesy** [comment]
> I'm also bumping into this issue. I'm running MacOS High Sierra too (npm v5.5.1 & node v8.7.0). The only way I could get it to work is by running `npm run dev`, and then running `npm run start` (in another tab) after Webpack had finished building. This brings up the UI and allows you to start using it. Not ideal, but it's a workaround at least.
> 
> The one thing I did find when running `npm run start` was that I get a few errors in my terminal. Not sure if it's specific to me though.
> 
> `rm: Medis.app/Contents/Resources/app.asar: No such file or directory`
> `[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0`

It works with `npm run dev`, and then running `npm run start`

**Comment by dejurin** [comment]
Catalina: I got the same problem

**Comment by hao830103** [comment]
Catalina +1
Same problem

**Comment by avillegas** [comment]
Catalina +1
Any update ?

**Comment by lyqeyes** [comment]
Why does there still has so much +1?  I opened the issue 3 years ago...  Some months ago, I cloned the repo and run those commands(updated as 3 years ago) follow the README.md. I remember that it can work as expected now.

Assuming U really has this problem, 

~~U can give a try to the app I packaged as follow.~~

aha, the .zip is so big that I can not upload it as an attachment. so U can 
1. try to package it by youself. u can use some utils like electron-packager
2. email me (lyq#oureda.cn) then I will send u the app package.  Tip: I have MAC app only.

**Comment by phuoc-insignia** [comment]
> > I'm also bumping into this issue. I'm running MacOS High Sierra too (npm v5.5.1 & node v8.7.0). The only way I could get it to work is by running `npm run dev`, and then running `npm run start` (in another tab) after Webpack had finished building. This brings up the UI and allows you to start using it. Not ideal, but it's a workaround at least.
> > The one thing I did find when running `npm run start` was that I get a few errors in my terminal. Not sure if it's specific to me though.
> > `rm: Medis.app/Contents/Resources/app.asar: No such file or directory`
> > `[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0`
> 
> It works with `npm run dev`, and then running `npm run start`

works for me

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
