### ISSUE TITLE
App Store build needs to be updated to 0.6.1

### ISSUE THREAD

**Issue by MilesOkeefe** [luin/medis#105]
The latest release on the App Store page for medis is version 0.6.0

**Comment by MilesOkeefe** [comment]
This should be assigned to @luin I assume

**Comment by nesl247** [comment]
Bumping this. Curious, is this app dead?

**Comment by luin** [comment]
Hi, sorry for the late response. 0.6.0 and 0.6.1 are same. There's no difference between them. It was  a bug of the build script that I had to bump the version just to trigger the build script again.

I'm a little busy these days. However, Any pull request for the bug fixes or new features are welcome.

**Comment by zedtux** [comment]
@luin if you're busy why not looking for contributors? Ask for help :)

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
