### ISSUE TITLE
Package errors

### ISSUE THREAD

**Issue by danieluyo** [luin/medis#106]
```
➜  medis git:(master) ✗ npm install
npm WARN extract-text-webpack-plugin@1.0.1 requires a peer of webpack@^1.9.11 but none is installed. You must install peer dependencies yourself.

up to date in 5.104s
➜  medis git:(master) ✗ npm install webpack@^1.9.11
npm WARN file-loader@1.1.5 requires a peer of webpack@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.

+ webpack@1.15.0
added 7 packages, removed 41 packages and updated 14 packages in 10.925s
➜  medis git:(master) ✗

➜  medis git:(master) ✗ npm install webpack@^2.0.0
npm WARN extract-text-webpack-plugin@1.0.1 requires a peer of webpack@^1.9.11 but none is installed. You must install peer dependencies yourself.
```

😑😑😑

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
