### ISSUE TITLE
npm run build or electron missing

### ISSUE THREAD

**Issue by prem911** [luin/medis#107]
"scripts": {
    "start": "rm Medis.app/Contents/Resources/app.asar; NODE_ENV=debug Medis.app/Contents/MacOS/Electron .",
    "dev": "./bin/dev",
    "deploy": "NODE_ENV=production ./bin/deploy",
    "release": "NODE_ENV=production ./bin/release",
    "sign": "./bin/sign",
    "unsign": "./bin/unsign",
    "tomedis": "./bin/tomedis"
  },

Scripts say some different commands!

**Comment by tom10271** [comment]
```
npm run build
npm ERR! missing script: build
```


What is going on.....

**Comment by tom10271** [comment]
I have tried script commands listed in packages.json and I still can't build the app successfully. Very disappointing

**Comment by abbood** [comment]
so..... what's this all about? what command should we run?

**Comment by fanjieqi** [comment]
The two commands are late:
```
$ npm run build
$ npm run electron
```
which should be:
```
$ npm run deploy
$ npm start
```

But the app launched has something wrong.

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
