### ISSUE TITLE
Search pattern能增加/是否有 排除功能？

### ISSUE THREAD

**Issue by chchleung** [luin/medis#108]
你好：
我知道pattern  可以 abc* 这样匹配，是否能提供 ^abc* 类似的 排除abc开头的key的筛选功能？感谢

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
