### ISSUE TITLE
Is there a way to select keys that don't begin with a pattern?

### ISSUE THREAD

**Issue by lovek323** [luin/medis#110]
The above title says it all. I need to exclude keys that don't begin with a certain pattern.

**Comment by luin** [comment]
Medis supports glob-style patterns:
h?llo matches hello, hallo and hxllo
h*llo matches hllo and heeeello
h[ae]llo matches hello and hallo, but not hillo
h[^e]llo matches hallo, hbllo, ... but not hello
h[a-b]llo matches hallo and hbllo

Refer to https://redis.io/commands/keys for details.
