### ISSUE TITLE
npm run pack error

### ISSUE THREAD

**Issue by Tank000** [luin/medis#114]
Tankmac:medis tanktan$ npm run pack

> medis@0.6.1 pack /Users/tanktan/Workspace/medis
> NODE_ENV=production npm run build -- -p --config webpack.production.config.js && node bin/pack.js

> medis@0.6.1 build /Users/tanktan/Workspace/medis
> webpack --progress --colors "-p" "--config" "webpack.production.config.js"

Hash: 9babf5a360a25f6b372b
Version: webpack 1.15.0
Time: 28166ms
            Asset     Size  Chunks             Chunk Names
          main.js  1.41 MB       0  [emitted]  main
patternManager.js   325 kB       1  [emitted]  patternManager
    + 552 hidden modules
Packaging app for platform mas x64 using electron v1.4.15
/Users/tanktan/Workspace/medis/bin/pack.js:24
    throw err;
    ^

Error: Command failed: npm prune --production
npm WARN fixed-data-table-contextmenu@1.6.5 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN fixed-data-table-contextmenu@1.6.5 requires a peer of react-dom@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: whatwg-fetch@2.0.3 (node_modules/_isomorphic-fetch@2.2.1@isomorphic-fetch/node_modules/whatwg-fetch):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/private/var/folders/09/00zwzvrn1lx3j9x3r030nt601403zl/T/electron-packager/mas-x64/Medis-mas-x64/Electron.app/Contents/Resources/app/node_modules/_isomorphic-fetch@2.2.1@isomorphic-fetch/node_modules/whatwg-fetch/package.json.599795548'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: asap@2.0.6 (node_modules/_promise@7.3.1@promise/node_modules/asap):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/private/var/folders/09/00zwzvrn1lx3j9x3r030nt601403zl/T/electron-packager/mas-x64/Medis-mas-x64/Electron.app/Contents/Resources/app/node_modules/_promise@7.3.1@promise/node_modules/asap/package.json.1717003281'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: isomorphic-fetch@2.2.1 (node_modules/_fbjs@0.8.16@fbjs/node_modules/isomorphic-fetch):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/private/var/folders/09/00zwzvrn1lx3j9x3r030nt601403zl/T/electron-packager/mas-x64/Medis-mas-x64/Electron.app/Contents/Resources/app/node_modules/_fbjs@0.8.16@fbjs/node_modules/isomorphic-fetch/package.json.416182329'

npm ERR! path /private/var/folders/09/00zwzvrn1lx3j9x3r030nt601403zl/T/electron-packager/mas-x64/Medis-mas-x64/Electron.app/Contents/Resources/app/node_modules/_isomorphic-fetch@2.2.1@isomorphic-fetch/node_modules/node-fetch/package.json.1736064846
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/private/var/folders/09/00zwzvrn1lx3j9x3r030nt601403zl/T/electron-packager/mas-x64/Medis-mas-x64/Electron.app/Contents/Resources/app/node_modules/_isomorphic-fetch@2.2.1@isomorphic-fetch/node_modules/node-fetch/package.json.1736064846'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tanktan/.npm/_logs/2018-01-11T01_49_25_516Z-debug.log

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! medis@0.6.1 pack: `NODE_ENV=production npm run build -- -p --config webpack.production.config.js && node bin/pack.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the medis@0.6.1 pack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tanktan/.npm/_logs/2018-01-11T01_49_25_612Z-debug.log

**Comment by 794322460** [comment]
i found an error like you, when i exec `npm install`, then appear this:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: medis@0.6.1
npm ERR! Found: webpack@1.15.0
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"^1.12.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^4.0.0 || ^5.0.0" from file-loader@6.2.0
npm ERR! node_modules/file-loader
npm ERR!   peer file-loader@"*" from url-loader@0.5.9
npm ERR!   node_modules/url-loader
npm ERR!     url-loader@"^0.5.7" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/bytedance/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bytedance/.npm/_logs/2021-05-18T03_47_53_197Z-debug.log



emm......

**Comment by Gauravself** [comment]
is it related to the npm version not being in sync with Webpack and dependencies versions? In other a degraded version of either npm,webpack, or updated versions of dependencies is required?

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
