### ISSUE TITLE
希望能增加像 Redis Desktop Manager 那样目录分类的显示方式。

### ISSUE THREAD

**Issue by doushichao** [luin/medis#115]
刚从 App Store 中购买，界面很 Mac，希望能增加像 Redis Desktop Manager 那样目录分类的显示方式。

**Comment by biezhi** [comment]
将使用 `:` 分隔的 `key` 做层级筛选，如果能做到像 `eclipse` 那样切换就更棒了 😄

**Comment by 127ice** [comment]
实用的功能，方便查看

**Comment by luin** [comment]
Supported in Medis v2. Sorry for the late response!

已经在 Medis v2 中加入，抱歉回复晚了
