### ISSUE TITLE
文档跟不上了

### ISSUE THREAD

**Issue by ljjsimon** [luin/medis#117]
readme 里
```
$ npm run build
$ npm run electron
```
这两个命令没有了
而且使用 npm run deploy 命令，得到的 medis.app 打不开
node 版本 v9.2.1
python 版本 2.7

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
