### ISSUE TITLE
nom run build script does not exist

### ISSUE THREAD

**Issue by vchouhan** [luin/medis#118]
After running npm install when we run npm build it throws error "missing script: build"

<img width="798" alt="image" src="https://user-images.githubusercontent.com/1222739/36814881-e478c4fe-1ca6-11e8-91f7-a07817eecc6a.png">

<img width="534" alt="image" src="https://user-images.githubusercontent.com/1222739/36814796-ae03165e-1ca6-11e8-84b1-83202bea019b.png">

**Comment by binygreenberg** [comment]
The two commands are late:

$ npm run build
$ npm run electron
which should be:

$ npm run deploy
$ npm start
But the app launched has something wrong.

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
