### ISSUE TITLE
Configure Font Size

### ISSUE THREAD

**Issue by ctzen** [luin/medis#120]
Please allow font (at least the font size) to be configured in preferences/settings.

**Comment by Arnie97** [comment]
The default font weight looks too light for me on a Mac. While I could modify the stylesheets (4917cc7b5a4869de890d7c42fffcba232058425d was a nice guide) and build it from scratch, it would be much easier if we add a item in the config tab for the CSS `font` property (which covers `font-family`, `font-size`, `font-weight`, `line-height` and so on).

**Comment by luin** [comment]
Sorry for the late reply. [Medis 2](https://getmedis.com/) allows font size customizing.

@dubiousdavid Thanks for the support! Feel free to LMK if there are anything we can do to improve on the font settings.
