### ISSUE TITLE
I cant Resize list of cache in redis

### ISSUE THREAD

**Issue by michaelhalim** [luin/medis#129]
I had problem, I dont know how to resize this list of cache...
I'm already set to full screen, but list of cache still in problem

I'm using mac Os High Sierra Version 10.13.4

![image](https://user-images.githubusercontent.com/39051387/41218628-ec523e14-6d85-11e8-9dbb-f8fb293dbbb8.png)

**Comment by luin** [comment]
Not an issue anymore in [Medis 2](https://getmedis.com/). Closing. Feel free to reopen if the issue persists.
