### ISSUE TITLE
Windows版本时不时就弹窗提示

### ISSUE THREAD

**Issue by zhuxuchao** [luin/medis#131]
![image](https://user-images.githubusercontent.com/32405152/42627748-82278d9e-8600-11e8-970f-2657979a64c1.png)

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
