### ISSUE TITLE
希望支持Redis 5.0的Stream

### ISSUE THREAD

**Issue by zxl777** [luin/medis#132]
Redis 5.0已经到RC3了，估计很快就要发布正式版，如果能支持Redis 5.0的新功能，特别是新的Stream数据类型，那就太好了。

**Comment by zxl777** [comment]
medis 现在还无法连接最新都Redis 5.0 RC3 server. 老的数据格式也读不到。

**Comment by asi6611622** [comment]
+1

**Comment by wangkang** [comment]
+1

**Comment by luin** [comment]
Supported in Medis v2. Sorry for the late response!
