### ISSUE TITLE
Pattern Manager TypeError

### ISSUE THREAD

**Issue by advicepyro** [luin/medis#134]
Opening the pattern manager, I get in the console: `Uncaught TypeError: Cannot read property 'get' of undefined` on `patternManager.js:46553`

**Comment by advicepyro** [comment]
I've worked around this for now by modifying the references to `activePattern` as such:

`value: this.state.name || (activePattern ? activePattern.get('name') : null)`

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
