### ISSUE TITLE
Invalid sentence in README.md

### ISSUE THREAD

**Issue by Beenhakker** [luin/medis#137]
The README.md states: "You can download compiled versions of Medis for Mac OS X from [the release page](https://github.com/luin/medis/releases).", but the compiled versions are nowhere to be found.

Just to let you know.

**Comment by olek-p** [comment]
Apart from that, when building from source, `npm run build` fails due to `missing script: build` (release 0.6.1).

**Comment by rainzhao** [comment]
README.md: 
local run 
```shell
$ npm install
$ npm run dev
```

## Build Medis

```shell
$ npm install
$ npm run deploy
```

**Comment by dimensi** [comment]
I try it, but got nothing

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
