### ISSUE TITLE
Self built app fails silently when ran.

### ISSUE THREAD

**Issue by Egoscio** [luin/medis#14]
I tried building and installing Medis locally by doing the following, as said in the readme:
```
$ npm install
$ npm run deploy
```
For some reason, whenever I run the resulting .app, it shows me an empty app GUI with no main window (ie: Only the toolbar). I tried debugging this by reverting and doing `npm run dev` instead of `deploy`, and it works fine when I `npm start`. It seems to me like something might be wrong with the deploy script, not completely sure though. The only problem with `npm run dev` is that when you run the .app, it shows you the generic "Drag your app here to run it" Electron window. I really have no idea how Electron packages the app binaries, so I'll just leave it to that for now.

**Comment by Egoscio** [comment]
Judging by the recent commits and new release, I assume that the problem has been resolved. Thanks!

**Comment by luin** [comment]
Sorry for the delay. I was struggling with the build scripts. I updated the README and let me know whether the new scripts work for you: https://github.com/luin/medis#running-locally

**Comment by Egoscio** [comment]
Thank you! I'll try it once I get home. The new release is working right now, I'll try building soon.
