### ISSUE TITLE
Redis Error: Connection failed. Connect ETIMEDOUT

### ISSUE THREAD

**Issue by feimosi** [luin/medis#142]
I'm getting the following error after connecting to Redis:
![image](https://user-images.githubusercontent.com/5721520/52066925-c18ca000-2579-11e9-8ae7-ed2d4288d349.png)

The credentials are valid and work in a CLI. What's interesting, I can see the current data on the left panel (it's updated).

Tested on Medis v0.6.1.39-1, Arch Linux.

**Comment by waynebloss** [comment]
Exact same setup here (v0.6.1.39-1 on Arch (Manjaro) Linux). CLI works, Medis doesn't. Using the Redis [docker image](https://hub.docker.com/_/redis).

I thought perhaps it could be some incompatibility with the very latest version of Redis since that's what I used. But, when I tested it with Redis version 4.0.12 the same problem happened.

**Comment by jonaslu** [comment]
:+1: Same here - arch linux and medis 0.6.1.39-1. ETIMEDOUT after a couple of seconds - application works fine until then

**Comment by jonaslu** [comment]
I did some more digging and I'm guessing it's a problem with the arch-package build and not medis in itself. If you check out this repo, build and run it it works fine on my arch installation.

I'm guessing the semver:s in package.json that made it break on arch: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=medis

The build seems to check out commit bb76f74112870d46cc6b6e033ab21ea4737a46d9 which is from 2017, when there was no package-lock.json. Then probably one of the dependencies in nedis got upated and via the semver-versioning included in the 2017 version and it magically broke.

I'll flag the ARCH package as out of date and this can probably be closed.

**Comment by darky** [comment]
0.7.1.16-1 bumped!
This issue can be closed

**Comment by feimosi** [comment]
I can confirm, works fine now.
