### ISSUE TITLE
Tree View

### ISSUE THREAD

**Issue by flipxfx** [luin/medis#15]
It would be nice to have a tree view to help navigate keys.

So if you have the following keys

```
internal123
user:1
user:2
```

The sidebar navigation could look like

```
internal123
user v
    1
    2
```

**Comment by luin** [comment]
As for me, tree view is a little overkill since most keys won't have more than two levels of depth.

Medis uses a pattern manager to help you manage your keys, and in a sense, it's similar to the tree view but more flexible.

**Comment by Gertt** [comment]
Would you consider adding this if a PR is provided?

**Comment by luin** [comment]
Sounds interesting. However, why do you need a tree view rather than the pattern manager? Furthermore, it would be a little hard to implement the tree view since `SCAN` command won't give you all the key prefixes in the database.
