### ISSUE TITLE
Please add Dark theme

### ISSUE THREAD

**Issue by makotia** [luin/medis#151]
I hope to support "Dark Theme".
Because recently OS (example: macOS Mojave, Windows 10) and many applications supported but medis isn't so.

**Comment by AxelPrieto** [comment]
It's been two years. Please consider this feature. Some of us rely on this for accessibility reasons.

**Comment by luin** [comment]
Added in [Medis 2](https://getmedis.com/). Feel free to upgrade and try it out. Thanks for using Medis!
