### ISSUE TITLE
Cannot copy text in terminal

### ISSUE THREAD

**Issue by technicallyfeasible** [luin/medis#152]
Maybe I am just missing something but Ctrl-C does not copy text selected in the terminal.

Steps to reproduce:
* go to terminal and run some command, for example SLOWLOG GET
* drag to select some text and press CTRL-C

Expected:
* the text has been copied to the clipboard and can be pasted with CTRL-V

Actual:
* nothing has been copied to the clipoard

Tested in Medis for Windows.

**Comment by luin** [comment]
Does this issue exists in the latest version. I tested with the latest code of the master branch and Copy/Paste works well. My OS is macOS.

**Comment by technicallyfeasible** [comment]
I just tested with the latest version compiled locally and the issue still exists. To be clear, I don't mean "copy text in the current input row" (where the cursor is).
I mean to copy text in the output of a previous command.
Both don't work though.

**Comment by technicallyfeasible** [comment]
I just did a couple more tests. It seems that only ctrl-c does not work in the terminal but going to the "Edit" menu and selecting "copy" does work perfectly.
Would be great if ctrl-c could be enabled but I think I can live with the edit menu

**Comment by luin** [comment]
Not an issue anymore in [Medis 2](https://getmedis.com/). Closing. Feel free to reopen if the issue persists.
