### ISSUE TITLE
mac 打包📦一直等待

### ISSUE THREAD

**Issue by justmd5** [luin/medis#155]
![image](https://user-images.githubusercontent.com/4120960/58159781-c94e8c80-7caf-11e9-8e08-71409baf1be8.png)
基于最新的master打包

**Comment by KGNexus5X** [comment]
```
Downloading tmp-35265-0-electron-v4.0.0-mas-x64.zip
[>                                            ] 0.1% of 53.67 MB (68.12 kB/s)
```
node bin/pack.js 你怕是卡在这了

**Comment by justmd5** [comment]
> ```
> Downloading tmp-35265-0-electron-v4.0.0-mas-x64.zip
> [>                                            ] 0.1% of 53.67 MB (68.12 kB/s)
> ```
> 
> node bin/pack.js 你怕是卡在这了

应该怎么处理

**Comment by KGNexus5X** [comment]
> > ```
> > Downloading tmp-35265-0-electron-v4.0.0-mas-x64.zip
> > [>                                            ] 0.1% of 53.67 MB (68.12 kB/s)
> > ```
> > 
> > 
> > node bin/pack.js 你怕是卡在这了
> 
> 应该怎么处理 @KGNexus5X
build到那直接取消, 再node bin/pack.js

**Comment by justmd5** [comment]
@luin 有空帮忙处理一下？感谢🙏
