### ISSUE TITLE
please support redis cluster

### ISSUE THREAD

**Issue by linxuanwei** [luin/medis#160]

**Comment by davelet** [comment]
还不打算支持吗 等的我花都谢了

**Comment by c-y-q** [comment]
> 还不打算支持吗 等的我花都谢了

it has supported, l have used it sucessfully

**Comment by chalince** [comment]
> > 还不打算支持吗 等的我花都谢了
> 
> it has supported, l have used it sucessfully

How to use it.

**Comment by GuanZFF** [comment]
How to connect the cluster

**Comment by luin** [comment]
Supported in 2.9.0. Any feedbacks are welcome! The latest version can be downloaded from https://getmedis.com/
