### ISSUE TITLE
How to specify the redis user when connecting to a Heroku redis server?

### ISSUE THREAD

**Issue by edelgado** [luin/medis#163]
https://github.com/luin/medis#connect-to-heroku mentions how to get the credentials, which is great, but it makes no mention as to how to specify the `USER` when connecting to a server. In the Medis connection UI, there is no field for the username. I'm unable to connect (timeout) and I believe is because I can't specify the user along with the host and port.

**Comment by taichunmin** [comment]
I think you don't need the user. Because Redis only need the `HOST`, `PORT` and `PASSWORD`.

**Comment by seawatts** [comment]
I am getting the same error, connection timeout. I am able to connect to the redis instance with other GUIs as well as the heroku UI, which says it is healthy.

**Comment by taichunmin** [comment]
1. create new app and add heroku redis
2. `heroku login` to login on Terminal
3. `heroku redis:credentials --app YOUR_APP_NAME`
```
redis://h:pe67a2c5f62c8eebff247573ee1dc728b6a540b16758df351c524f284xxxxxxxx@ec2-52-22-xxx-xx.compute-1.amazonaws.com:28079
```
4. Use the following data to login
    - Redis Host: `ec2-52-22-xxx-xx.compute-1.amazonaws.com`
    - Port: 28079
    - Password: `pe67a2c5f62c8eebff247573ee1dc728b6a540b16758df351c524f284xxxxxxxx`

**Comment by seawatts** [comment]
Yeah I tried that. Still doesn't work

**Comment by taichunmin** [comment]
![](https://i.imgur.com/iuKZUdY.png)

**Comment by taichunmin** [comment]
![截圖 2019-11-27 11 04 18](https://user-images.githubusercontent.com/2192626/69690079-9f19d380-1105-11ea-8013-6a82d38d9d5f.png)

**Comment by seawatts** [comment]
Yeah that is what I tried. No go

**Comment by luin** [comment]
Sorry for the late response! Username support is introduced in Medis v2. Closing
