### ISSUE TITLE
can't show window in mac OS Mojave

### ISSUE THREAD

**Issue by YouLiLiao** [luin/medis#164]
I'm install medis in mac OS Mojave, the installation is complete, but after executing "npm start", no window is displayed.

**Comment by liqingbao** [comment]
same issue

**Comment by Amit-A** [comment]
same here

**Comment by VonSandberg** [comment]
same same...

**Comment by daniesy** [comment]
Try running `npm run dev`, and then in another tab `npm run start`

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
