### ISSUE TITLE
Binary keys don't work

### ISSUE THREAD

**Issue by bilgorajskim** [luin/medis#168]
Binary keys are listed, but with "NONE" type and they can't be viewed:

<img width="1072" alt="Screenshot 2019-11-09 at 16 00 07" src="https://user-images.githubusercontent.com/5052636/68530618-167bf480-030a-11ea-8c17-fe11e60fd974.png">

Redis supports binary keys:

`
Redis keys are binary safe, this means that you can use any binary sequence as a key, from a string like "foo" to the content of a JPEG file. The empty string is also a valid key.
`
https://redis.io/topics/data-types-intro

I think the issue is because Medis is calling TYPE command here:
https://github.com/luin/medis/blob/c5b5094abfdc8fdc40dfae8657acc3cd21c3c6a1/src/renderer/windows/MainWindow/InstanceContent/DatabaseContainer/Content/index.jsx#L25
**and gets "none" in response**. This may be because Medis is altering the key somewhere in a way that changes its binary structure, so Redis sees it as a different, non existing key.

**Comment by luin** [comment]
Added in Medis v2. Sorry for the late response.
