### ISSUE TITLE
any way to support hot reload?

### ISSUE THREAD

**Issue by zzz6519003** [luin/medis#17]

**Comment by luin** [comment]
Hot reloading during development? Webpack should support it with a few changes on `webpack.config.js`. Haven't looked into it though.

**Comment by zzz6519003** [comment]
:beer:

2016-02-15 9:22 GMT+08:00 Zihua Li <notifications@github.com>:

> Hot reloading during development? Webpack should support it with a few
> changes on webpack.config.js. Haven't looked into it though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/luin/medis/issues/17#issuecomment-184018855>.
>



-- 


yours,

正中赵
about.me/zzz6519003
[image: 正中赵 on about.me]
  <http://about.me/zzz6519003>

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
