### ISSUE TITLE
希望加入key精确搜索，目前搜索太慢

### ISSUE THREAD

**Issue by iiinsomnia** [luin/medis#174]

**Comment by iiinsomnia** [comment]
类似阿里云这样：

![image](https://user-images.githubusercontent.com/6582246/71864589-23b33500-313b-11ea-9605-b7c2cb8814fb.png)

**Comment by luin** [comment]
Hi @iiinsomnia 👋 

Medis 2 默认会自动执行精确搜索。希望能满足你的需求。任何问题欢迎随时反馈。
