### ISSUE TITLE
RedisJSON support?

### ISSUE THREAD

**Issue by kunaakos** [luin/medis#178]
Hi! I cannot see the values of RedisJSON entries. I suppose they are not supported yet. Would it be possible to add support?
 
<img width="952" alt="Screenshot 2020-02-28 at 16 22 37" src="https://user-images.githubusercontent.com/3966787/75561066-a9ba7080-5a46-11ea-980e-b42f510d24fa.png">

**Comment by MatthD** [comment]
This could be very cool indeed +1

**Comment by Androz2091** [comment]
Yes, I'm using this app and it's useless without the support for redisjson as I can't see all my keys 
...

**Comment by luin** [comment]
Added in Medis v2. Sorry for the late response.
