### ISSUE TITLE
Feature Request: Multiple selection of keys (and properties within sets/lists/etc)

### ISSUE THREAD

**Issue by rex** [luin/medis#18]
My team just picked up Medis and boy oh boy is it a breath of fresh air :D In :heart: with it so far. There are a few quirks that I wanted to create some tickets for here as feedback/requests but overall this is a fantastic piece of software that we are excited to start using!

Like I said, I didn't want to jam multiple things into the same issue so that they could be addressed separately from one another. 
## Multiple Selection

Having the ability to <kbd>ctrl</kbd> or <kbd>cmd ⌘</kbd> + click to select multiple items and act on them simultaneously would be a _tremendous_ help when interacting with a large data set, _especially_ when deleting large numbers of items. 

What are your thoughts?

**Comment by lutics** [comment]
Is any update on this issue?

**Comment by luin** [comment]
This is already supported by Medis 2 with `CMD` + click so closing. Free free to create a new issue if there is anything else we can improve!
