### ISSUE TITLE
Base64 format support

### ISSUE THREAD

**Issue by chrisronline** [luin/medis#185]
Great utility! Thanks for all the work.

I'm currently storing base64-encoded JSON strings in my Redis DB and I'd love this tool to work for that use case. I'm not sure if this is a common setup, but the changes were pretty minor to get working (See https://github.com/luin/medis/compare/master...chrisronline:base64?expand=1)

Any interest for me to turn this into a PR?

**Comment by luin** [comment]
Hey @chrisronline 👋 

Thanks for the contribution! We have shifted our efforts to Medis 2. And the latest Medis 2 release has provided Base64 format support! Please try it out https://getmedis.com/. LMK if there are any questions!
