### ISSUE TITLE
DB不能选择

### ISSUE THREAD

**Issue by alberliu** [luin/medis#186]
![image](https://user-images.githubusercontent.com/24761362/81785543-02bb8000-9531-11ea-89ad-11ef209fa666.png)
我通过ssh链接redis,然后进去之后DB不能选择，如果不通过ssh连接正常

**Comment by ihipop** [comment]
第一次链接是可以选择的，选一次以后就不能选了。
但是看起来这个项目作者已经弃坑了

**Comment by luin** [comment]
奇怪，我这边是可以的（即使是 SSH）。有可以重现的方式吗？

**Comment by ihipop** [comment]
> 奇怪，我这边是可以的（即使是 SSH）。有可以重现的方式吗？

@luin 走ssh链接 redis，然后选一次db切换一下，再点那个选db的菜单 就选不了。只有切换后的db一个选项

**Comment by okdanta** [comment]
@luin redis只有16个库的时候是可以切换的。当我换成一个拥有256个库的redis之后，就出现了题主说的情况了。

**Comment by hardy4yooz** [comment]
> 奇怪，我这边是可以的（即使是 SSH）。有可以重现的方式吗？

应该是和db的数量有关系。阿里云255个db只能第一次打开。

**Comment by mitoop** [comment]
我也遇到不能选择的问题，在我这必重新。也是连接的阿里云。每次我都是手动执行命令 select dbindex。。。这么好的软件 为啥不更新了 @luin

**Comment by luin** [comment]
@mitoop
感谢询问！在写 Medis 2，重写了大部分代码。因为最近结婚所以进度有点慢，计划7月底能发布第一个版本。这个版本中会引入这些修改。

**Comment by mitoop** [comment]
> @mitoop
> 
> 感谢询问！在写 Medis 2，重写了大部分代码。因为最近结婚所以进度有点慢，计划7月底能发布第一个版本。这个版本中会引入这些修改。

👍 期待啊 大佬刚结婚啊 最近我已经切换多个redis客户端了 那就等medis2了

**Comment by luin** [comment]
@mitoop Medis 2 已经发布了，可以在 https://apps.apple.com/us/app/medis-2-gui-for-redis/id1579200037?mt=12 上免费下载（或者在 macOS App Store 上搜索 Medis 2）。

**Comment by mitoop** [comment]
@luin 下载了 medis 2 对于medis 1 付过费的用户没有什么优惠吗？ 60美元 略贵啊

**Comment by luin** [comment]
@mitoop 调整了一下价格，近期不会变啦。之前研究了一下，App Store 的付费机制实现不了针对 Medis 1 用户的优惠，所以只能心里感谢了！不过 Medis 2 的付费卡点比较宽松，大部分个人用户轻度使用的话都是可以免费用的。有什么功能期望欢迎 medis@zihua.li 告诉我。

**Comment by mitoop** [comment]
好的 主要是想支持一下 基本功能日常够用了

**Comment by ihipop** [comment]
> @mitoop 调整了一下价格，近期不会变啦。之前研究了一下，App Store 的付费机制实现不了针对 Medis 1 用户的优惠，所以只能心里感谢了！不过 Medis 2 的付费卡点比较宽松，大部分个人用户轻度使用的话都是可以免费用的。有什么功能期望欢迎 [medis@zihua.li](mailto:medis@zihua.li) 告诉我。

所以现在仓库里面的是2.0的代码么？

**Comment by luin** [comment]
@ihipop 仓库中是 1.0 的代码。因为已经在新版中支持，所以我关闭这个 ticket 了。如果有任何问题，欢迎随时反馈 👋
