### ISSUE TITLE
[Feature Request] Pattern history

### ISSUE THREAD

**Issue by drahnieR** [luin/medis#197]
Currently, there's "Manage Patterns". But it's too much work if I just want to jump across different keys temporarily.

**Comment by musicin3d** [comment]
I'm working on this, because it's an easy way to get started with contributing. I've already got a working prototype that keeps the latest 5 patterns. I will submit a PR after I clean it up.

**Comment by luin** [comment]
Hey @drahnieR @musicin3d 👋 ,

Thanks for raising this up and the contribution! This feature has already landed with [Medis v2](https://getmedis.com/) so closing this. Feel free to lmk if there are anything else missing.
