### ISSUE TITLE
Updating host erases saved patterns

### ISSUE THREAD

**Issue by musicin3d** [luin/medis#202]
1. save a redis connection and connect
1. save one or more patterns
1. disconnect
1. change the redis host
1. save and connect

Result: saved patterns are gone

Expected: saved patterns are still available

**Comment by musicin3d** [comment]
I discovered that setting the host back to the original value restores all the saved patterns! So they're still saved. It appears that they are keyed by the hostname instead of a unique id. I'll find a solution and submit a PR.

**Comment by musicin3d** [comment]
That's not at all what's happening. This is going to take longer that I expected.

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
