### ISSUE TITLE
[Urgent] need update the version of node-sass and related extension

### ISSUE THREAD

**Issue by rizsky** [luin/medis#208]
`node-sass@3.13.1` already removed from git

this is evidence when i try to install it 
![image](https://user-images.githubusercontent.com/43275779/99625359-ab0f4b80-2a62-11eb-817e-e6248e2adc25.png)

instead i update node-sass@3.13.1 to `v5.0.0 (latest)` it seems work fine

please recheck the dependancies

**Comment by mirsch** [comment]
related to #207

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
