### ISSUE TITLE
npm run pack 打包报错

### ISSUE THREAD

**Issue by jiell** [luin/medis#209]
ERROR in ./node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/slicedToArray.js
    Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/arrayWithHoles' in '/Users/jiel/code/github/medis/node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm'
     @ ./node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/slicedToArray.js 1:0-71 6:9-23
     @ ./node_modules/_react-sortable-hoc@1.11.0@react-sortable-hoc/dist/react-sortable-hoc.esm.js
     @ ./src/renderer/windows/MainWindow/InstanceTabs/Tabs.tsx
     @ ./src/renderer/windows/MainWindow/InstanceTabs/index.tsx
     @ ./src/renderer/windows/MainWindow/index.jsx
     @ ./src/renderer/windows/MainWindow/entry.jsx
    
    ERROR in ./node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/toConsumableArray.js
    Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/arrayWithoutHoles' in '/Users/jiel/code/github/medis/node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm'
     @ ./node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/toConsumableArray.js 1:0-77 6:9-26
     @ ./node_modules/_react-sortable-hoc@1.11.0@react-sortable-hoc/dist/react-sortable-hoc.esm.js
     @ ./src/renderer/windows/MainWindow/InstanceTabs/Tabs.tsx
     @ ./src/renderer/windows/MainWindow/InstanceTabs/index.tsx
     @ ./src/renderer/windows/MainWindow/index.jsx
     @ ./src/renderer/windows/MainWindow/entry.jsx
    
    ERROR in ./node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/possibleConstructorReturn.js
    Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/assertThisInitialized' in '/Users/jiel/code/github/medis/node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm'
     @ ./node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/possibleConstructorReturn.js 2:0-85 8:9-30
     @ ./node_modules/_react-sortable-hoc@1.11.0@react-sortable-hoc/dist/react-sortable-hoc.esm.js
     @ ./src/renderer/windows/MainWindow/InstanceTabs/Tabs.tsx
     @ ./src/renderer/windows/MainWindow/InstanceTabs/index.tsx
     @ ./src/renderer/windows/MainWindow/index.jsx
     @ ./src/renderer/windows/MainWindow/entry.jsx
    
    ERROR in ./node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/objectSpread.js
    Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/defineProperty' in '/Users/jiel/code/github/medis/node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm'
     @ ./node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/objectSpread.js 1:0-71 14:6-20
     @ ./node_modules/_react-sortable-hoc@1.11.0@react-sortable-hoc/dist/react-sortable-hoc.esm.js
     @ ./src/renderer/windows/MainWindow/InstanceTabs/Tabs.tsx
     @ ./src/renderer/windows/MainWindow/InstanceTabs/index.tsx
     @ ./src/renderer/windows/MainWindow/index.jsx
     @ ./src/renderer/windows/MainWindow/entry.jsx
    
    ERROR in ./node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/toConsumableArray.js
    Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/iterableToArray' in '/Users/jiel/code/github/medis/node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm'
     @ ./node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/toConsumableArray.js 2:0-73 6:35-50
     @ ./node_modules/_react-sortable-hoc@1.11.0@react-sortable-hoc/dist/react-sortable-hoc.esm.js
     @ ./src/renderer/windows/MainWindow/InstanceTabs/Tabs.tsx
     @ ./src/renderer/windows/MainWindow/InstanceTabs/index.tsx
     @ ./src/renderer/windows/MainWindow/index.jsx
     @ ./src/renderer/windows/MainWindow/entry.jsx
    
    ERROR in ./node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/slicedToArray.js
    Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/iterableToArrayLimit' in '/Users/jiel/code/github/medis/node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm'
     @ ./node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/slicedToArray.js 2:0-83 6:32-52
     @ ./node_modules/_react-sortable-hoc@1.11.0@react-sortable-hoc/dist/react-sortable-hoc.esm.js
     @ ./src/renderer/windows/MainWindow/InstanceTabs/Tabs.tsx
     @ ./src/renderer/windows/MainWindow/InstanceTabs/index.tsx
     @ ./src/renderer/windows/MainWindow/index.jsx
     @ ./src/renderer/windows/MainWindow/entry.jsx
    
    ERROR in ./node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/slicedToArray.js
    Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/nonIterableRest' in '/Users/jiel/code/github/medis/node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm'
     @ ./node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/slicedToArray.js 4:0-73 6:102-117
     @ ./node_modules/_react-sortable-hoc@1.11.0@react-sortable-hoc/dist/react-sortable-hoc.esm.js
     @ ./src/renderer/windows/MainWindow/InstanceTabs/Tabs.tsx
     @ ./src/renderer/windows/MainWindow/InstanceTabs/index.tsx
     @ ./src/renderer/windows/MainWindow/index.jsx
     @ ./src/renderer/windows/MainWindow/entry.jsx
    
    ERROR in ./node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/toConsumableArray.js
    Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/nonIterableSpread' in '/Users/jiel/code/github/medis/node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm'
     @ ./node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/toConsumableArray.js 4:0-77 6:94-111
     @ ./node_modules/_react-sortable-hoc@1.11.0@react-sortable-hoc/dist/react-sortable-hoc.esm.js
     @ ./src/renderer/windows/MainWindow/InstanceTabs/Tabs.tsx
     @ ./src/renderer/windows/MainWindow/InstanceTabs/index.tsx
     @ ./src/renderer/windows/MainWindow/index.jsx
     @ ./src/renderer/windows/MainWindow/entry.jsx
    
    ERROR in ./node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/inherits.js
    Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/setPrototypeOf' in '/Users/jiel/code/github/medis/node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm'
     @ ./node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/inherits.js 1:0-71 14:18-32
     @ ./node_modules/_react-sortable-hoc@1.11.0@react-sortable-hoc/dist/react-sortable-hoc.esm.js
     @ ./src/renderer/windows/MainWindow/InstanceTabs/Tabs.tsx
     @ ./src/renderer/windows/MainWindow/InstanceTabs/index.tsx
     @ ./src/renderer/windows/MainWindow/index.jsx
     @ ./src/renderer/windows/MainWindow/entry.jsx
    
    ERROR in ./node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/possibleConstructorReturn.js
    Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/typeof' in '/Users/jiel/code/github/medis/node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm'
     @ ./node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/possibleConstructorReturn.js 1:0-56 4:15-22
     @ ./node_modules/_react-sortable-hoc@1.11.0@react-sortable-hoc/dist/react-sortable-hoc.esm.js
     @ ./src/renderer/windows/MainWindow/InstanceTabs/Tabs.tsx
     @ ./src/renderer/windows/MainWindow/InstanceTabs/index.tsx
     @ ./src/renderer/windows/MainWindow/index.jsx
     @ ./src/renderer/windows/MainWindow/entry.jsx
    
    ERROR in ./node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/slicedToArray.js
    Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/unsupportedIterableToArray' in '/Users/jiel/code/github/medis/node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm'
     @ ./node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/slicedToArray.js 3:0-95 6:64-90
     @ ./node_modules/_react-sortable-hoc@1.11.0@react-sortable-hoc/dist/react-sortable-hoc.esm.js
     @ ./src/renderer/windows/MainWindow/InstanceTabs/Tabs.tsx
     @ ./src/renderer/windows/MainWindow/InstanceTabs/index.tsx
     @ ./src/renderer/windows/MainWindow/index.jsx
     @ ./src/renderer/windows/MainWindow/entry.jsx
    
    ERROR in ./node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/toConsumableArray.js
    Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/unsupportedIterableToArray' in '/Users/jiel/code/github/medis/node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm'
     @ ./node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/toConsumableArray.js 3:0-95 6:59-85
     @ ./node_modules/_react-sortable-hoc@1.11.0@react-sortable-hoc/dist/react-sortable-hoc.esm.js
     @ ./src/renderer/windows/MainWindow/InstanceTabs/Tabs.tsx
     @ ./src/renderer/windows/MainWindow/InstanceTabs/index.tsx
     @ ./src/renderer/windows/MainWindow/index.jsx
     @ ./src/renderer/windows/MainWindow/entry.jsx
    
    ERROR in [at-loader] TS2688: Cannot find type definition file for 'node'.

**Comment by jiell** [comment]
node -v
v15.2.1

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
