### ISSUE TITLE
Disable certificate check for SSL connections

### ISSUE THREAD

**Issue by kayman-mk** [luin/medis#211]
I discovered a problem in my development environment where the ssl certificates used do not match the host I am connecting to. 

I use Medis to connect to my cloud Redis instance via a bastion host and port forwarding. As my Medis connection is created with host = localhost, but the server certificate has "localhost" not included, Medis complains with "Hostname doesn't match certificate's altnames". But in this case it would be helpful to disable the check. How to disable the check / any chance that something like this can be implemented?

I tried the SSH tunnel feature. But authentication works with key files here and I wasn't able to configure this in Medis.
I tried to setup the server's certificate in the "Certificate" section of the SSL configuration. But it didn't work.

But nevertheless: It's a great tool. Thank you.

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
