### ISSUE TITLE
npm start: `electron not found`

### ISSUE THREAD

**Issue by kylebakerio** [luin/medis#213]
```bash
$ npm start

> medis@1.0.3 start
> electron .

sh: 1: electron: not found
npm ERR! code 127
npm ERR! path /home/kyle/code/forks/medis
npm ERR! command failed
npm ERR! command sh -c electron .

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kyle/.npm/_logs/2021-03-01T01_37_20_911Z-debug.log
```

this is after running npm install (which failed, needed python installed--new machine!), then npm run pack (which opens a browser session and then leaves a running process; do I need to leave that running or something...?_, then npm start. :/

**Comment by kylebakerio** [comment]
i ended up manually installing electrion with 'npm install electron' (even though it is in the dependencies and I had run npm install?). Then when I would run npm start I got an error from electron telling me there was no electron app. then I had to run the pack command again, and _then_ npm run start seemed to work. weird.

**Comment by warapitiya** [comment]
try

```sh
npm run build
npm run start
```

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
