### ISSUE TITLE
fresh installed ubuntu 20.10 has numerous gotchas

### ISSUE THREAD

**Issue by kylebakerio** [luin/medis#222]
my OS got nuked, so I'm having to go through this again, but on a very clean install, so might be helpful to others/maintainer(s):

Pop_OS 20.10 (ubuntu 20.10 variant)

clone
npm install
get errors 
npm install
no errors?
npm install again
errors again?
weird...
npm run pack
webpack not installed
*sigh*
check here
npm run build?
webpack not installed...

check errors, first one is:
"chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies."

Looks like I need to downgrade node for this to work. :/

nvm install 14
node -v 
-> 14.16.0
npm install
much better this time, but hit error. First error I see:
gyp verb check python checking for Python executable "python2" in the PATH
I only have python3, guess I need to go get python2
sudo apt install python2
npm install
seems to work this time

npm run pack

hmm... no error, but seems to hang. last lines I see:
```sh
        Entrypoint mini-css-extract-plugin = *
        [0] ./src/renderer/photon/fonts/photon-entypo.eot 82 bytes {0} [built]
        [1] ./node_modules/css-loader/dist/cjs.js!./src/renderer/photon/css/photon.min.css 24.1 KiB {0} [built]
        [4] ./src/renderer/photon/fonts/photon-entypo.woff 83 bytes {0} [built]
        [5] ./src/renderer/photon/fonts/photon-entypo.ttf 82 bytes {0} [built]
            + 2 hidden modules
```

I run it again, but then I notice this seems to start a local server that shows a tree of its packages or something, so... probably when it 'hangs' I can just kill and move on...?

indeed,

npm start

now works.

cool. Anyways, just sharing. Hope it helps others.

**Comment by ssi-anik** [comment]
Without doing this much, you can just download the app image from https://github.com/baryon/medis

#235 
I just downloaded for Ubuntu 20.04 and it's working fine.

**Comment by armujahid** [comment]
Thanks @ssi-anik AppImage is also working fine with Ubuntu 22.04 after installing fuse `sudo apt-get install fuse libfuse2`

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
