### ISSUE TITLE
Apple Silicon support?

### ISSUE THREAD

**Issue by dalisoft** [luin/medis#223]
Hi @luin.
I purchased this app few month ago and now purchased M1 MacBook, would be nice to see Apple Silicon binary support

**Comment by dalisoft** [comment]
@luin If there v2 version was made for Apple Silicon, so we get some discount for v2 who purchased Medis (v1)?

**Comment by luin** [comment]
Hi @dalisoft,

Thanks for asking! We did consider the discount thing but unfortunately, it doesn't work with Apple's IAP system. However, most features in Medis v2 are free so hope that can fit your need. Anyway, thanks for the support and for using Medis 1!
