### ISSUE TITLE
Can't run SENTINEL command in Medis 2

### ISSUE THREAD

**Issue by dubiousdavid** [luin/medis#238]
I can't run the following valid command using Medis 2:

```
SENTINEL get-master-addr-by-name mymaster
```

**Comment by luin** [comment]
Hey @dubiousdavid 👋

Not sure why I have missed this ticket. Sorry for that! Confirmed and will get it fixed soon!

**Comment by luin** [comment]
Resolved. Closing. Thanks for the feedback.
