### ISSUE TITLE
medis 2: ERR unknown command 'hsetns'

### ISSUE THREAD

**Issue by MakDon** [luin/medis#239]
Error when new row in hash:

> ERR unknown command 'hsetns'

Should use hsetnx instead?

![image](https://user-images.githubusercontent.com/19908547/131960088-7c002689-4391-4334-ac0c-21196425e5ed.png)

**Comment by MakDon** [comment]
Version: Version 2.1.3 (1471)

**Comment by luin** [comment]
Hi @MakDon !
Thanks for using Medis! Yes, it's a bug. We will get it fixed soon!

**Comment by luin** [comment]
Fixed in 2.3.0.
