### ISSUE TITLE
Medis 2 on Homebrew

### ISSUE THREAD

**Issue by gvko** [luin/medis#244]
Can we get Medis 2 on [Homebrew](https://brew.sh/)?

**Comment by luin** [comment]
It's only available on the Mac App Store for now. Any pros to have it on Homebrew?

**Comment by gvko** [comment]
> It's only available on the Mac App Store for now. Any pros to have it on Homebrew?

Yeah, I know, I installed it from the AppStore. 
But to answer your question about any benefits: mostly ease of installation. I tend to install most of the apps thru Homebrew and keep a list of installation commands.

**Comment by morilog** [comment]
I was needed this too. I am from IRAN and because of sanctions I can not sign-in to the app store. So I could not download the Medis GUI.

**Comment by LeoAJ** [comment]
+1, my company did not support app store in company laptop. `Homebrew` will be a better option

**Comment by tkambler** [comment]
Installing it from the app store is a challenge in my corporate environment, as well.

**Comment by luin** [comment]
We are going to make it possible in the next couple of weeks and will post updates here.

**Comment by luin** [comment]
Hi all, Medis 2 is now available on the website: https://getmedis.com/ so you can download it outside of the App Store. I already submitted it on HomeBrew: https://github.com/Homebrew/homebrew-cask/pull/123039.

Any feedbacks are welcome!

**Comment by luin** [comment]
Added the instructions to the homepage https://getmedis.com/. Closing
