### ISSUE TITLE
medis2 精确搜索的问题

### ISSUE THREAD

**Issue by ydq** [luin/medis#245]
medis2 **精确搜索** 依旧使用的是scan，导致如果key巨多的话 就会很慢

都 **精确** 了，是不是应该使用 get 会更好一点？

线上环境超1亿的key，为了精确查找一个key，结果扫描了好久好久，最终还是改用命令窗口去执行……

![image](https://user-images.githubusercontent.com/8097340/144962580-a5903936-50ab-4f30-9d0b-f20f1a12bef4.png)

实际上要查询的 key 没有通配符，即便是用scan 也只会有一条结果，毕竟是 **精确** 查询

![image](https://user-images.githubusercontent.com/8097340/144962666-0e87777b-c28e-46be-988a-fc0772680530.png)

**Comment by luin** [comment]
感谢反馈！是个问题，会尽快修复。

**Comment by luin** [comment]
@ydq 2.6.5 版本已经修复了这个问题
