### ISSUE TITLE
How to get the invoice?

### ISSUE THREAD

**Issue by Kikobeats** [luin/medis#246]
I paid for Medis 2 via App Store but looks like the service doesn't generate an invoice 🤔

**Comment by luin** [comment]
Thanks for supporting Medis!

To get a receipt on iOS:
Settings->Apple ID (the first item)->Media & Purchases->View Account->Purchase History. Find Medis and click resend.

**Comment by Kikobeats** [comment]
got it, thanks for the quick reply 🙂
