### ISSUE TITLE
UTF8 encoded

### ISSUE THREAD

**Issue by davidesigner** [luin/medis#248]
Thanks for this new version of Medis. Many cool options availables!

The only regression from the 1st version is that UTF8 characters stay encoded...

The new one:
<img width="400" alt="Capture d’écran 2022-02-08 à 09 10 26" src="https://user-images.githubusercontent.com/13423202/152944853-8d340712-0594-4509-ab01-4c54aa7d04ab.png">

The version 1:
<img width="400" alt="Capture d’écran 2022-02-08 à 09 10 16" src="https://user-images.githubusercontent.com/13423202/152944842-3e7eb08c-5b74-4739-8577-ceca29646224.png">

Is there anything to do to have human readable characters?

**Comment by luin** [comment]
Hey @davidesigner 👋 

Thanks for using Medis! I can't reproduce this with 2.7.0. Are there any special chars that don't render properly?

<img width="722" alt="CleanShot 2022-02-12 at 11 07 37@2x" src="https://user-images.githubusercontent.com/635902/153694395-46a3d676-57fd-42ef-9e4c-17d325cbb811.png">

**Comment by davidesigner** [comment]
Hi @luin,

Thanks for your reply, sorry for my late reply...

My Redis documents are encoded:
```json
{"id":"selection-e8667b64-4985-45e9-a960-3243c1dffd96","openedBlocks":["Informations importantes","Bien pr\u00e9parer votre s\u00e9jour","Suggestions de vols"]}
```

The first version of Medis display decoded characters when I choose the JSON format:

<img width="960" alt="v1-raw" src="https://user-images.githubusercontent.com/13423202/161144442-2f3e322c-65f0-4c12-b98b-82cf2362c3db.png">

<img width="960" alt="v1-json" src="https://user-images.githubusercontent.com/13423202/161144456-5429b4d3-7d8d-402e-b462-eee0f4d1745a.png">


The new version for the same document:

<img width="894" alt="v2-json" src="https://user-images.githubusercontent.com/13423202/161144623-454fa1a5-3597-47ea-b939-0ab9de907cbd.png">

**Comment by luin** [comment]
Sorry for the late response. According to the spec of JSON, it's valid to encode Unicode chars with `\uxxxx`. The difference between Medis 1 and 2 is that Medis 1 parses the \uxxxx code, while Medis 2 displays it as is. Comparing the two I prefer the behavior of Medis 2, which shows the original content of the database.

Let me know if that makes sense. Thanks for using Medis!

**Comment by davidesigner** [comment]
I find it interesting that the "raw" format of the document is really raw and therefore not parsed. Especially to detect a bug or understand what is really stored.

When we display a JSON version, we are in a consultation / edition process. And at this moment, to see the pretty small sun ☀️  is more practical than to see `\u2600`.

Are you agree?

**Comment by luin** [comment]
@davidesigner @benjamindulau Yeah I think an option to toggle the behavior would be useful. Added to the roadmap.

**Comment by davidesigner** [comment]
Hi @luin, thanks for your comment.

Where could we find the progress of this issue? Do you have any idea of the expected release date?

**Comment by luin** [comment]
Hey @davidesigner! Sorry for the slow progress! Will be released in the next version (within a month).

**Comment by luin** [comment]
[Medis 2.zip](https://github.com/luin/medis/files/10286497/Medis.2.zip)

Here is a beta version and would be great if you have a chance to give it a try.

**Comment by davidesigner** [comment]
Thanks for the beta version @luin, what is this option you've added?

For information, when I try to switch to any default Encoders, I have the following message:
<img width="1239" alt="Capture d’écran 2022-12-22 à 17 05 50" src="https://user-images.githubusercontent.com/13423202/209174678-3f926666-ce9b-417f-905f-caf73b42d110.png">

**Comment by luin** [comment]
![CleanShot 2022-12-23 at 08 01 37@2x](https://user-images.githubusercontent.com/635902/209245209-d7b6072a-805b-483d-9f67-0378bf71bd8b.png)

It's on the Editor setting panel.

**Comment by davidesigner** [comment]
Awesome (I didn't find it because I was using the bad version sorry), that's working great! Thanks @luin
