### ISSUE TITLE
Feature request: Python pickle support

### ISSUE THREAD

**Issue by dan-blanchard** [luin/medis#261]
It is fairly common for people using django to store [pickled](https://docs.python.org/3/library/pickle.html) responses in redis. It would be very nice if medis supported properly displaying pickled response. I saw on npm there are [several libraries](https://www.npmjs.com/search?q=pickle%20python) that claim to support unpickling in Javascript, so maybe this isn't that crazy of an ask?

Currently, medis seems to always detect them as `Viewer: JSON, Formatter: MessagePack`, which makes it look like an empty dict, even though there's data there. I have to switch to `Viewer: Hex, Formatter: None` to be able to see anything.

**Comment by luin** [comment]
Hey @dan-blanchard 👋,

Glad to add more formatters to Medis. A question is pickled data may contain tuple, classes and other data structures that can't be represented in JSON, do you have any suggestions how Medis should present them?

> which makes it look like an empty dict, even though there's data there

Going to take a look as I think it's a bug that Medis detect pickled data as MessagePack.

**Comment by luin** [comment]
2.8.13 fixed the wrong detection for pickle so it should default to `Viewer: Hex, Formatter: None`.

**Comment by dan-blanchard** [comment]
> do you have any suggestions how Medis should present them?

Python classes can store data in two possible places: a `__dict__` dictionary (which is pretty easily convertible to JSON), or in individual attributes listed in `__slots__`. The second format is also convertible to a dictionary/JSON-object as described [here](https://stackoverflow.com/questions/21682774/how-can-i-convert-python-class-with-slots-to-dictionary) by iterating through the list of attributes and then getting the values of each.

My preference would be to display the Python classes as JSON objects, with the extra attribute `__class__` set, so you could tell what class each object represented.

**Comment by luin** [comment]
I am going to support custom encoders in https://github.com/luin/medis/issues/262. For pickle support, you should be able to create an encoder. LMK if there are any improvements I can do.
