### ISSUE TITLE
Feature request: nippy or transit or more via shell script "viewers"?

### ISSUE THREAD

**Issue by rgm** [luin/medis#262]
Hi, clojurist here. I saw in #261 a request for Python pickle detection, and have a similar feature request, but more general. First, I use a lot of nippy and transit, which are pretty niche:

https://github.com/ptaoussanis/nippy
https://github.com/cognitect/transit-format

I've scoped out a similar idea/feature request for Paw.app and it's just not realistic to expect it's worth anyone's time to support these directly.

BUT I'd like to open discussion for the idea of custom "viewers" as user-provided shell scripts that transform from Redis data to plain text or perhaps HTML (for hierarchy). Then it opens up the viewers as a sort of plug-in system. We have composable shell tools like https://github.com/borkdude/jet for examining this data off the wire ... maybe a good way to support these formats is using STDIN and STDOUT and any script that transforms `arbitrary data -> text` can be used.

**Comment by luin** [comment]
Hey @rgm 👋 ,

Thanks for the feature request. That sounds good. Added this to the roadmap.

**Comment by luin** [comment]
The alpha version is here: https://www.dropbox.com/s/p1cgsq0vp8iylny/Medis.zip?dl=0. Would be great if you can give it a try 😄. The instruction can be found in the app setting:

<img width="572" alt="CleanShot 2022-07-21 at 12 22 28@2x" src="https://user-images.githubusercontent.com/635902/180129369-ef8a5f03-e525-41df-9e90-1d8b1d80eaa2.png">

**Comment by rgm** [comment]
Amazing! I'll try it out today. 🙏

**Comment by luin** [comment]
The feature was just released! 🎉
Also, another feature Content rules is included so you are able to specify the default viewer/encoder for keys that match a certain rule.
