### ISSUE TITLE
Support ~/.ssh/config and SSH ProxyJump

### ISSUE THREAD

**Issue by christianseel** [luin/medis#263]
It seems like medis is not using the ~/.ssh/config file for ssh connections and so not using the `ProxyJump` I configured in my config.

I need to connect to a remote redis server, which is only accessible via a remote host (web server). And I can only access the web server via our teams ssh hopper (the ssh jump server).

```
my machine ---ssh---> team jump server ---ssh---> web server ---redis---> redis server
```

Am I doing something wrong or is it not (yet?) supported by Medis 2?

I'm using Medis Version 2.8.17 (3060) on a MacBook Pro M1 (ARM) with macOS 12.2.1 (21D62).

**Comment by luin** [comment]
Hey @christianseel 👋

Thanks for using Medis! Currently Medis does not read the ssh config file due to the sandbox restrictions.

However, Medis provides options to set up the connection to SSH servers. Are there any other options Medis need to provide in order to connect to the jump server?

**Comment by christianseel** [comment]
Hi @luin , thanks for getting back so quickly! Understanding the sandbox issue - makes sense.

Medis currently only can connect to a redis server via 1 ssh connection, like:
```
my machine ---ssh---> web server ---redis---> redis server
```

What I need is an additional ssh jump before connecting the that "web server", like:
```
my machine ---ssh---> team jump server ---ssh---> web server ---redis---> redis server
```

I guess Medis would need an additional "SSH ProxyJump" configuration option to configure the ssh jump host. Is that understandable?

**Comment by luin** [comment]
That makes sense. Thanks for the explanation! I'm thinking about providing a way to let users give Medis access to the SSH config file so Medis can use it directly. Will get back to you when I have an update on this.

**Comment by luin** [comment]
I just added a panel on the application preference (CMD+,) and you should be able to select your SSH config file. Here is a beta version if you want to test it out:

[Medis SSH.zip](https://github.com/luin/medis/files/9264853/Medis.SSH.zip)

Feedbacks are welcome!

**Comment by christianseel** [comment]
Awesome! Confirming that works fine as expected! 👏🏻 

SSH-Config for the redis server now just needs one of the alias from the ssh config and it uses those settings! Really awesome!

Looking forward to the release on the App Store :)

Feel free to close the issue whenever you want.

**Comment by luin** [comment]
The new version just gets released on the App Store. Feel free to let me know if you have other questions!
