### ISSUE TITLE
Problem with Cluster without rejectUnauthorized option

### ISSUE THREAD

**Issue by ZPVIP** [luin/medis#265]
l'd like to add a `rejectUnauthorized: false` as a cluster option.

`rejectUnauthorized: false` doesn't disable SSL but disables server certificate verification. 

or leave a empty text area, allow user to add their own options.

Thanks!

**Comment by luin** [comment]
Hi 👋 

Thanks for using Medis! It's already the default option and actually we are going to add an option to perform authorization for SSL connections.
