### ISSUE TITLE
Feature request: log window

### ISSUE THREAD

**Issue by chiefy** [luin/medis#27]
Trying to diagnose why my connection is timing out, it'd be really handy to see any warnings etc that are being thrown. Thanks!

**Comment by luin** [comment]
When did the timing out happen? Connecting to the Redis server or executing commands?

**Comment by chiefy** [comment]
@luin connecting to redis. it's really bizarre, it's an Elasticache node, and I can connect to it via `redis-cli` but not w/ medis. Not seeing anything in syslog. Any way to debug?

**Comment by luin** [comment]
There's no log window now, but I would like to add it in the next version. For now, you can build a development version (`npm run dev`) and enable the web developer tool (Option + Command + I) to see if there's any error.

**Comment by chiefy** [comment]
Thanks @luin
