### ISSUE TITLE
Feature Request - Sort Hash field by key

### ISSUE THREAD

**Issue by careerlister** [luin/medis#271]
Sorting the field column in a hash would be super helpful.  I know that REDIS doesn't organize data this way but when it comes to a reader / client the extra step to sort alphabetically the HKEYS and make Medis easier to use.  Clicking on "Field" looks like it maybe a button but it doesn't do anything.

Thanks in advance.

**Comment by luin** [comment]
Added to the roadmap. Thanks for the feature request! We'll probably let Medis check if the hash size is small enough (< ~2000 fields) and alert users if not.

**Comment by luin** [comment]
Implemented and released in the non-app store version (can download from https://getmedis.com/). The app store version will be released in the next week.

Thanks for the suggestion!
