### ISSUE TITLE
Unsupported key type MBbloom 

### ISSUE THREAD

**Issue by mitoop** [luin/medis#272]
用了这个插件 [RedisBloom](https://github.com/RedisBloom/RedisBloom), Medis提示Unsupported key type MBbloom. 这个有办法支持吗? 
<img width="391" alt="image" src="https://user-images.githubusercontent.com/7368344/199063995-1eefdbb6-11c1-4fd7-828c-4739c27e4cd1.png">

**Comment by luin** [comment]
您好 @mitoop 👋 ,

可以考虑加入到开发计划中。看起来 RedisBloom 主要是用来判断一个元素是不是在一个集合里。您希望 Medis 能为此提供什么功能呢？

感谢使用 Medis！

**Comment by mitoop** [comment]
有时间了可以加一下 😊  没啥需求, 就是看下数据发现不支持😂 
感谢
