### ISSUE TITLE
aws redis 链接问题

### ISSUE THREAD

**Issue by xiongbenwu** [luin/medis#276]
我看到选项里有 集群支持，但是我想通过ssh 方式链接进群如何实现呢

**Comment by luin** [comment]
感谢使用 Medis！因为性能原因，集群目前还不支持 SSH 方式。建议可以做一个跳板机来中转，这样也更安全

**Comment by luin** [comment]
最新版已经支持了 SSH + 集群功能，欢迎使用！有问题随时联系。
