### ISSUE TITLE
medis在mac上使用当点了X体验异常

### ISSUE THREAD

**Issue by sheniceice** [luin/medis#28]
在mac上，感觉medis当我打开窗口，然后使用完，点击了X关闭后，当再一次需要使用时，点击dock中的medis图标会弹不出客户端。而是要将当前的客户端退出之后重新连接，这应该是一个问题吧。

**Comment by luin** [comment]
是的，可以按 Command + N 来新建窗口。下个版本会尝试修复

**Comment by sheniceice** [comment]
嗯嗯，感觉很好用，就是这个问题有点影响体验，已加星！

**Comment by luin** [comment]
已经解决，多谢反馈！
