### ISSUE TITLE
Don't able to use cluster mode with ssh tunnel

### ISSUE THREAD

**Issue by VsevolodChumachenko** [luin/medis#280]
Buid: 3078
Version: 2.9.4
OS: macOS Ventura 13.0.1

<img width="551" alt="Снимок экрана 2023-01-10 в 14 21 28" src="https://user-images.githubusercontent.com/53918248/211538659-d0296cd2-7f2d-40b6-9d11-19349f0ac8da.png">

**Comment by luin** [comment]
Hey @VsevolodChumachenko 👋 

Thanks for using Medis! Due to performance reasons, we don't support Cluster via SSH Tunnels as a cluster may contain many nodes and the performance impact would be noticeable if we create an SSH tunnel for each connection. You may want to set up an SSH jump server or VPN to handle that.

**Comment by VsevolodChumachenko** [comment]
> Hey @VsevolodChumachenko 👋
> 
> Thanks for using Medis! Due to performance reasons, we don't support Cluster via SSH Tunnels as a cluster may contain many nodes and the performance impact would be noticeable if we create an SSH tunnel for each connection. You may want to set up an SSH jump server or VPN to handle that.

I also use "Another Desktop Manager" and it supports ssh tunnel + cluster. I haven't noticed any perfomance problems with that.
![image](https://user-images.githubusercontent.com/53918248/232488871-be2e465d-5936-4124-ae9d-e65597822e4e.png)

**Comment by VsevolodChumachenko** [comment]
I also use "Another Desktop Manager" and it supports cluster + ssh tunnel. I haven't noticed any performance problems. It will be great if you add this opportunity.
![image](https://user-images.githubusercontent.com/53918248/232489065-079f2e9d-ee01-42a1-b0c4-f33705b83219.png)

**Comment by luin** [comment]
Yeah we added it to the roadmap. Do you need NAT or host redirections? For example, in the connection config, the SSH host is ssh.com and Redis host is 127.0.0.1. In your use case, does `CLUSTER NODES` command return nodes with host of `127.0.0.1` or you need to set up some redirections?

**Comment by luin** [comment]
Hi @VsevolodChumachenko, this is added in the latest version.
