### ISSUE TITLE
Bug report: "Restore Purchase" button doesn't work

### ISSUE THREAD

**Issue by dilame** [luin/medis#281]
I would like to buy the license on medis website and apply it using "Restore Purchase", but this button just does nothing.
My installation is MacBook M1 Pro MasOS through AppStore.

**Comment by luin** [comment]
Hey @dilame 👋 

Thanks for using Medis! You can download Medis from the official website https://getmedis.com with the "Download Free Trial" button. Please refer to https://getmedis.com/pricing#:~:text=Should%20I%20buy%20Medis%20on%20the%20Mac%20App%20Store%20or%20from%20your%20website%3F for details.
