### ISSUE TITLE
Key type json

### ISSUE THREAD

**Issue by mequelussi** [luin/medis#285]
I use redis from upstash and use the JSON type, but medis says it is not compatible

**Comment by luin** [comment]
Hi 👋. Can you post a screenshot?

**Comment by mequelussi** [comment]
<img width="318" alt="Captura de Tela 2023-02-16 às 20 10 12" src="https://user-images.githubusercontent.com/22084507/219508752-ac1b8229-93bc-428e-bb49-ce588a0efc02.png">

**Comment by luin** [comment]
Hi 👋. Can you post a screenshot?

**Comment by mequelussi** [comment]
<img width="1205" alt="Captura de Tela 2023-02-16 às 20 11 28" src="https://user-images.githubusercontent.com/22084507/219508881-3ce606cf-21f1-499f-b841-23819b222368.png">

**Comment by luin** [comment]
@mequelussi Looks like it's Upstash specific: https://upstash.com/blog/redis-json. We are going to investigate this.

**Comment by chronark** [comment]
Hey, I'm working at upstash.

We should be api compatible with the official redis json, please let me know if there are any issues

**Comment by luin** [comment]
The support has just been added and is now waiting for the App Store review 😄. It didn't work because Medis didn't recognize the response of `"json"` returned by `TYPE` command (it expected `"rejson-rl"` for json keys) although the API is compatible.

**Comment by chronark** [comment]
ok great, can't wait to try it out
thank you so much

**Comment by luin** [comment]
Released in the latest version 🎉. Closing...
