### ISSUE TITLE
Feature request: Support custom grouping for all servers

### ISSUE THREAD

**Issue by silenceu** [luin/medis#286]
Hi, I'm using Medis 2 now. It's a very great production 👏.

May I know if there is any plan to add a **tag** attribute to the server connection to support the filter, or support creating a server collection? When there are multiple servers in different business scenarios, I think it would be more friendly for server management.

**Comment by luin** [comment]
Thanks for using Medis! We are working on two improvements related to what you requested.

The first is that you can now assign colors to connections so it should help you to differentiate different environments:
![image](https://user-images.githubusercontent.com/635902/221102757-8c2cb9b2-11a3-4753-a9b5-3fd1fba962cd.jpeg)

The other is folder/group support.

I think that should fit your needs? Let me know if there are anything else we can improve 😊

**Comment by song-huang** [comment]
Wow, look great, Looking forward to it. Thanksss!

**Comment by luin** [comment]
This has been already released on https://getmedis.com. The app store version will be released in the next week.

**Comment by luin** [comment]
The app store version has been released. Closing...Feel free to let me know if there is anything we can improve.
