### ISSUE TITLE
Medis2 supports set font ?

### ISSUE THREAD

**Issue by shenghui0779** [luin/medis#287]

**Comment by luin** [comment]
It doesn't for now. Can you share your use cases so we can evaluate it? Thanks for using Medis!

**Comment by shenghui0779** [comment]
纯属想换自己喜欢的字体

**Comment by luin** [comment]
了解。是编辑器的字体吗？还是左侧键列表的字体？

**Comment by shenghui0779** [comment]
能同时支持最好了😊

**Comment by luin** [comment]
<img width="449" alt="CleanShot 2023-05-14 at 16 46 30@2x" src="https://github.com/luin/medis/assets/635902/4b24ab89-f77f-47ac-b1d2-a0aa06b01aac">

久等了，下个版本会加上字体选择。

**Comment by shenghui0779** [comment]
赞！
