### ISSUE TITLE
Allow horizontal scrolling of content pane

### ISSUE THREAD

**Issue by stitch** [luin/medis#302]
Hi Luin,

I'd like to compare multiple values at a certain part in the content, but there is no way to scroll horizontally. I cannot make my screen / window wide enough to compare these values. Can horizontal scrolling be added to the content pane?

![image](https://github.com/luin/medis/assets/333846/e896d0e8-ae59-498c-9223-c62b18402e87)

**Comment by luin** [comment]
Hey @stitch 👋 

Thanks for the feedback! I think that makes sense. Added to the roadmap.

**Comment by luin** [comment]
Implemented and released in the non-app store version (can download from https://getmedis.com/). The app store version will be released in the next week.

Thanks for the suggestion!
