### ISSUE TITLE
1Password SSH Agent Support

### ISSUE THREAD

**Issue by fosron** [luin/medis#304]
Can you add support for this https://developer.1password.com/docs/ssh/agent/ ? Only being able to select a file limits SSH key management.

An example of this is TablePlus DB app - they use ssh config if no key is selected 
![Screenshot 2023-12-01 at 12 05 00](https://github.com/luin/medis/assets/3708631/ec766360-8df2-4602-a851-ad221fe8d5ce)

**Comment by fosron** [comment]
@luin it still requires me to select a key, and i can't do that as 1Password based key is not a file.

**Comment by nklmilojevic** [comment]
I think this won't ever work if you do not offer using Medis outside of appstore, maybe an opportunity to sell it through website rather than just AppStore?

**Comment by fosron** [comment]
I agree. Seems that its not going to work like that, so non-sandboxed version of the app is the only option here sadly.

**Comment by nklmilojevic** [comment]
Apologies for pinging once more - is there any way to transfer the license from AppStore to the version that is on the website?

**Comment by luin** [comment]
@nklmilojevic I'd love to help! Can you forward your MAS receipt (`subject:(Your receipt from Apple)`) to medis@zihua.li?

**Comment by luin** [comment]
Looks like it works perfectly now with 1Password's nightly version. I added a page in the documentation site: https://docs.getmedis.com/integrations/1password-ssh-agent. Closing.
