### ISSUE TITLE
Selecting Databases Beyond the Default Range in Amazon ElastiCache

### ISSUE THREAD

**Issue by seolys** [luin/medis#307]
Hello,

I am currently using Amazon ElastiCache and have gone beyond using 15 databases. For instance, my service utilizes Database 48. However, in Medis, I can only select from databases 0 to 15.

I am curious about how I can select a database number greater than 15.

Thank you.

---

[DataGrip]
![image](https://github.com/luin/medis/assets/49857359/999fc5cc-9020-4201-a20a-4a22daa76dd5)

[Medis]
![image](https://github.com/luin/medis/assets/49857359/bf57ba68-7370-42ac-b0e1-2acc50846bfa)

**Comment by luin** [comment]
Thanks for using Medis! Would you upgrade Medis to the [latest version](https://getmedis.com/) and see whether this is fixed?

If you are already on the latest version, can you try running the following commands and see what's the output? Medis rely on those commands to get the database count in the sever:

1. `CONFIG GET DATABASES`: This is the primary way for Medis to get the db count.
2. `INFO KEYSPACE`: If the above command is not available in the server, Medis would fallback to this command. However, this command only reports database indexes that contains at least one key, so empty databases would be ignored.

While Medis doesn't show your db, you can still switch db in Medis's query window by running `SELECT n` to switch to db with index n. This can be considered as a workaround.

**Comment by luin** [comment]
Closing for now. Feel free to reopen if the issue persists.

**Comment by seolys** [comment]
Wow. It works very well! Thank you.
