### ISSUE TITLE
Can you subscribe to a topic/channel in medis?

### ISSUE THREAD

**Issue by jduprey** [luin/medis#31]
Is it possible to subscribe and view content that is published to a topic/channel?

**Comment by luin** [comment]
You can switch to the Terminal tab and run `subscribe xxx` command to subscribe channels.

**Comment by jduprey** [comment]
I would be great if medis could capture the data from the stream and render it like the other data.

**Comment by luin** [comment]
What do the "the other data" mean? Do you mean render the publish events like key list?

**Comment by jduprey** [comment]
Yes, that's what I meant.

**Comment by luin** [comment]
This is already supported by [Medis 2](https://getmedis.com/). Free free to create a new issue if there is anything else we can improve!
