### ISSUE TITLE
How do you compare with Redsmin & RDM

### ISSUE THREAD

**Issue by FGRibreau** [luin/medis#4]
Hello Zihua :)

I wonder, how do you compare with a GUI like **[Redsmin](https://redsmin.com)** ?

**Comment by hezhao** [comment]
Redsmin is not free (30-day free)
RDM has bad UI, it groups keys with colons like Windows Explorer.
Medis is free and it looks nice.

**Comment by FGRibreau** [comment]
Oh ok thanks for your answer :)
Please note that Redsmin is free forever with one server :)

**Comment by luin** [comment]
Hi @FGRibreau!
Actually I have never used them, and I'll definitely give them a try 😄. I just saw their introduction and both them are full featured GUI tools.
