### ISSUE TITLE
Unable to connect via ssl

### ISSUE THREAD

**Issue by niemyjski** [luin/medis#41]
By default azure hosted redis instances require ssl:

http://stackoverflow.com/questions/23773279/connecting-to-azure-redis-cache

I don't seem to be able to connect with ssl `........cache.windows.net,ssl=True`

**Comment by runger1101001** [comment]
Same problem here. Would love SSL support for the Azure use case. I'm willing to pay a $50 prize for this feature.

**Comment by luin** [comment]
I purchased a Redis instance on RedisLabs and just opened a ticket to enable the ssl support for my instance so that I can test against it. I'm going to implement the feature this week.
