### ISSUE TITLE
Feature Request: Custom Renderers 

### ISSUE THREAD

**Issue by atreides322** [luin/medis#43]
It would be really useful if either through some sort of plugin type system or through the use of an external command, if it were possible to create custom renderers of data.

For instance, I have a Java process that unfortunately stores values as a Java ObjectStream, and it would be nice if I could invoke a java process that would be able to take the data, deserialize it, and pass it back to Medis for display.

**Comment by luin** [comment]
Sorry for the late response after 7 years 😄. This has already been supported by Medis 2: https://docs.getmedis.com/settings/custom-encoders.
