### ISSUE TITLE
How could I use ‘FAVORITES'？收藏怎么用？

### ISSUE THREAD

**Issue by duzhipeng** [luin/medis#45]
![qq20161116-0](https://cloud.githubusercontent.com/assets/3648161/20341381/fe1ac8b4-ac20-11e6-9cd4-e8e9d46ae64b.png)

I find the ‘FAVORITES'  in the menu of the window,but I do not know how to use.
Help me please!
我在软件界面上看到一个FAVORITES，但不知道怎么用。
请求大神帮助！

**Comment by luin** [comment]
![image](https://cloud.githubusercontent.com/assets/635902/20342638/3c2412dc-ac26-11e6-8ee3-e8b6cfec84f8.png)
Check out the buttons on the lower left corner.

**Comment by duzhipeng** [comment]
> Check out the buttons on the lower left corner.

好勒~看到了。的确不明显呢~是国人我就不再发英文了，233333~

**Comment by luin** [comment]
嗯啊之前有人问过同样的问题...有机会我想想怎么改进
