### ISSUE TITLE
Import/Export Favourites

### ISSUE THREAD

**Issue by tillkruss** [luin/medis#46]
I was able to migrate the `Local Storage` directory, but I would be really nice if it were possible to import and export "Favourites".

**Comment by ziadoz** [comment]
The full directory path for anyone else trying to do this is: `~/Library/Containers/li.zihua.medis/Data/Library/Application Support/Medis/Local Storage `

**Comment by fgilio** [comment]
Were you able to "export" the favorites by copying the `Local Storage` dir? It's not working for me

**Comment by luin** [comment]
Supported in Medis 2. Sorry for the (7-year) delay
