### ISSUE TITLE
#建议# Content窗口底部请您考虑是否能优化一下

### ISSUE THREAD

**Issue by duzhipeng** [luin/medis#48]
内容要是多了，底部会重叠，影响查看和操作（比如操作勾选框覆盖的文字就很困难）。这里建议作者您考虑下一版顺手优化一下。
<img width="680" alt="qq20161121-0 2x" src="https://cloud.githubusercontent.com/assets/3648161/20468717/638a5f82-afd4-11e6-9ee1-b7fe79069c48.png">

**Comment by luin** [comment]
嗯确实，我平常用也遇到了这个问题，下个版本会优化

**Comment by yangg** [comment]
加个样式就好了，[参考](https://github.com/yangg/medis/commit/8d93e8377c588c2f6c5783d2eea9a19183ec41e2)
