### ISSUE TITLE
DB number can not be selected

### ISSUE THREAD

**Issue by basehibino** [luin/medis#51]
![2016-12-15 11 26 46](https://cloud.githubusercontent.com/assets/12025609/21209776/b4bcf9e4-c2b9-11e6-8696-d2d9fac5f80b.png)
![2016-12-15 11 26 55](https://cloud.githubusercontent.com/assets/12025609/21209780/b99e5e12-c2b9-11e6-8568-144d97af90ec.png)
DB number can not be selected. ↑There are things that I can and can not do. Why?

**Comment by luin** [comment]
This should be fixed in the latest version. What version are you using?

**Comment by basehibino** [comment]
0.3.1
I got it in App Store for Mac

**Comment by luin** [comment]
The new version is waiting for the review, and will be ready in a week or so.

This issue is caused by some SaaS services' not providing the interface of fetching db count.

Thank you for using Medis!

**Comment by basehibino** [comment]
Thank you

**Comment by luin** [comment]
@basehibino Hi, the latest version is available on the App Store. Feel free to check it out and please let me know if there's any problem.

**Comment by luin** [comment]
Aha, sorry just found you submitted another issue. I'll reply on that issue.

**Comment by basehibino** [comment]
Succeeded with SELECT 1 !!!!

I connect Amazon ElastiCache using a proxy.
It may be a special usage.

**Comment by luin** [comment]
Got it. I'll find an ElastiCache instance to test and will try to resolve this issue within this week. Thank you for the report!

**Comment by luin** [comment]
Hi @basehibino, sorry for the late response. The problem should be solved in the 0.6.0 (which will be available on App Store in 7days).
