### ISSUE TITLE
DB number can only be selected as 0

### ISSUE THREAD

**Issue by basehibino** [luin/medis#52]
![img_2572](https://cloud.githubusercontent.com/assets/12025609/21302608/94f536f4-c5fb-11e6-88b9-adc14b25a870.JPG)
How can I select DB number 1?
It is confirmed that DB number 1 exists.

**Comment by basehibino** [comment]
v 0.5.4

**Comment by luin** [comment]
Hey @basehibino, are you using a SaaS redis service (e.g. RedisLab)?

Currently there's a workaround for the issue: Switch to "Terminal" tab and invoke `SELECT 1` to select the db 1. The keys shown on the left panel will refresh automatically.

**Comment by schmod** [comment]
Having the same issue with AWS ElastiCache Redis.

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
