### ISSUE TITLE
Filter set members and hashes keys

### ISSUE THREAD

**Issue by kuroisuna** [luin/medis#54]
First of all, thanks you a lot for your effort.

It would be cool if we could filter through set members and hashes keys, I know that redis doesn't have a built in way to do this, maybe a simple javascript filterer...

Something like this:

![image](https://cloud.githubusercontent.com/assets/4406617/21436442/7d6900d0-c84c-11e6-86cd-fc2a5edb4e73.png)

**Comment by luin** [comment]
Added in [Medis 2](https://getmedis.com/). Feel free to upgrade and try it out. Thanks for using Medis!

Also, sorry for the late response, ...after 6 years 😄 .
