### ISSUE TITLE
😭为什么不是中文版

### ISSUE THREAD

**Issue by liujinyang1994** [luin/medis#57]
看到非常喜欢，在app store 看又是中文版，结果果断支持一下，结果下回来发现没有地方选语言。哭啊

**Comment by luin** [comment]
您好，感谢支持 Medis！刚才去看了一下，果然“语言”中除了英语还有很多其他的语言，找了一下没有找到设置的地方。问了其他人才知道在哪里设置。发下一个版本时我会修改一下语言列表。不过我会尝试在之后的版本加上语言选择支持。

因为 Medis 里面的英文很少，主要集中在连接设置里，如果您有哪里看不懂欢迎邮件或者 issue 询问。非常抱歉！

**Comment by liujinyang1994** [comment]
@luin 感谢你的回复，看到简体中文总有一种情怀😁
