### ISSUE TITLE
能在左边Key栏增加多选功能么

### ISSUE THREAD

**Issue by blakejia** [luin/medis#63]
因为在开发的时候经常碰到一些老数据，然而一条条删实在太慢了。
另外，希望能保存上次退出时的状态。

**Comment by luin** [comment]
嗯，多选只是为了批量删除吗？还有什么场景呢？

**Comment by blakejia** [comment]
暂时只想到这个需求。
另外希望能支持到快捷键command ＋ F 。可以切换到搜索的输入栏。谢谢

**Comment by luin** [comment]
好的，下个版本会加上 Command + F 快捷键。批量删除我再想一想

**Comment by yaoxinghuo** [comment]
多选还可以批量把key移到另一个db，不过好像当前也没有移到另一个db的功能。

**Comment by luin** [comment]
已经在 Medis 2 中支持。抱歉回复晚了（5年后 😂）

> 多选还可以批量把key移到另一个db，不过好像当前也没有移到另一个db的功能。

已经列到 Medis 2 的开发计划中。
