### ISSUE TITLE
 binary built locally cannot open on my mac

### ISSUE THREAD

**Issue by tobyforever** [luin/medis#64]
I followed the instruction but the generated binary Medis.app cannot open on my mac 10.11.6.  the connection window didn't show up. the size of the binary is 105.9M.

**Comment by Jergoo** [comment]
run into the same problem with upstairs

**Comment by luin** [comment]
That's strange. I'll look into it on this weekend.

**Comment by chuanconggao** [comment]
Run into the same issue. 

It works when I do the following
```bash
npm install
npm run dev
npm start
```

However, this does not work
```bash
npm install
npm run deploy
```

**Comment by luin** [comment]
What's the version of npm did you use? I'm using npm v2 and it works fine. Seems to be caused by the different dependency directory structures generated by npm v2 and npm v3.

**Comment by chuanconggao** [comment]
@luin My npm version is 4.4.0 and my node.js version is 7.6.0.

**Comment by pkumza** [comment]
I met this problem too.
use

**Comment by yaoxinghuo** [comment]
'npm run deploy' can show  the main window, but click 'About Medis', won't show the right version number.

<img width="284" alt="qq20170227-171117 2x" src="https://cloud.githubusercontent.com/assets/69723/23355239/cfcd65d0-fd0f-11e6-86d2-30bff9bc50c5.png">

**Comment by zxl777** [comment]
+1

**Comment by baryon** [comment]
如@luin 所说，使用npm v2编译确实可以启动，但是 @yaoxinghuo 的贴图的version还是无法显示。使用npmbrew可以自由切换npm版本

**Comment by sergeymakinen** [comment]
To fix `#version#` issues after `npm run deploy` run

```bash
perl -pi -e "s/#version#/$(cat package.json | json version)/g" ./Medis.app/Contents/Info.plist
```

You will need a `json` module: `npm install -g json`

I have copied it from `bin/release`.

**Comment by SumonMSelim** [comment]
Facing the same issue. The build is not working on my macOS.

**Comment by jhonyf** [comment]
Using nvm, I installed node version 4.8 which has npm 2 and with that I was able to build and open the app 

```
nvm install 4.8
nvm use 4.8
npm install
npm run deploy
```

**Comment by stepheneb** [comment]
Similar problems using:

```
$ node -v
v7.7.4
$ npm -v
4.1.2
```

**Comment by krazyjakee** [comment]
Builds fine but displays no window on osx.

```
$ npm -v
4.2.0
$ node -v
v7.9.0
```
Hiding a successful build behind a paywall is pretty dumb because if a drive-by contributor can't easily see how something is supposed to work, why would he ever stop to take a look? This project has developed painfully slowly because of that decision.

I'd argue that the complete lack of documentation on building is also deliberate. I'd also argue that there is something very fishy about the deploy/release not working. If you don't want developers to contribute to your open source software, remove it from github and stop wasting their time.

**Comment by stepheneb** [comment]
check out #77 and this commit: 0e4ae58a1de in ogasawaraShinnosuke fork

Medis now builds and runs for me.

**Comment by doublesharp** [comment]
@krazyjakee does it work if you try my fork in https://github.com/luin/medis/issues/73?

**Comment by rmariuzzo** [comment]
It worked for me:

 1. Download latest version from release page.
 2. Used latest Node 4.x version (using tj/n).
 3. Ran: `npm install`, then `npm deploy`.

Profit!

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
