### ISSUE TITLE
刷新数据时不要让布局也跟着刷新

### ISSUE THREAD

**Issue by baryon** [luin/medis#65]
为了看清楚数据，调整了中间这一栏的宽度，但是每次点刷新数据按钮的时候，中间一览的宽度又变回去了。
能不能刷新数据时不要让布局也跟着刷新

**Comment by luin** [comment]
是指 LIST, SET, ZSET 这些数据的列表宽度吗？了解，下个版本会改进

**Comment by luin** [comment]
已经在 master 上线了，完整测试后会发布到 App Store。
