### ISSUE TITLE
跪求 PHP 的 serialize 的消息格式

### ISSUE THREAD

**Issue by tsunamilx** [luin/medis#66]
好吧，我承认这是一个自私的请求。

作为 PHP 程序员，有时候用到 [序列化](http://php.net/manual/en/function.serialize.php) 和 [反序列化](http://php.net/manual/en/function.unserialize.php)，尤其在 [Laravel](http://laravel.com/) 中普遍都是。

**Comment by lawulu** [comment]
我需要一个Gzip版的..对React不熟，翻了下没找到在哪里Wrapper。或者可否提供一种能自定义序列化的机制？

**Comment by luin** [comment]
@lawulu 看来可以做成扩展形式了...我想想🤔

**Comment by tankerkiller125** [comment]
Since this project is built using NodeJS I think https://github.com/naholyr/js-php-unserialize may be of interest here

**Comment by luin** [comment]
Added in [Medis 2](https://getmedis.com/). Feel free to upgrade and try it out. Thanks for using Medis!
