### ISSUE TITLE
How can i connect mac homestead?

### ISSUE THREAD

**Issue by thirdriver** [luin/medis#68]
<img width="493" alt="qq20170313-115209 2x" src="https://cloud.githubusercontent.com/assets/9215420/23840836/8c09d322-07e3-11e7-8de9-1f86fb67fb7c.png">

I try default password but it can not work!

**Comment by luin** [comment]
What's "mac homestead"?

**Comment by newiep** [comment]
You can comment out the IP binding configuration.

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
