### ISSUE TITLE
Panel sizes and width are reset when browsing different ZSETs

### ISSUE THREAD

**Issue by atellier** [luin/medis#69]
Hi!

I have small suggestion that would make browsing ZSETs much easier: can we keep the width of the panel and columns persistent when browsing / clicking on different keys in ZSET (for instance). 

A lot of time, the initial second panel (the one with the members in the set) is too small and the columns (for the score for instance) is not wide enough, and I have to resize them. When I click on another ZSET / key, they get reset every time and I have to resize them again ;(

Thanks for that great Redis GUI!

**Comment by atellier** [comment]
Two other suggestions, also related to browsing ZSETs:

1/ It would be great to have a "refresh" button for the content of ZSETs as well. May be next to the "+" sign also. Now I have to click on another key and click back to refresh the list of members of a set.

2/ List will "follow" highlighted row when using UP / DOWN keys to browse keys in the list. If I use the UP / DOWN keys to navigate the list, the highlighted row will disappear at the bottom, and the window does not scroll automatically to "follow" the row.

No big deals, but would make the whole navigation / browsing of keys / sets a lot easier.

Thanks!

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
