### ISSUE TITLE
repository is slow to clone because of large binary files in Medis.app

### ISSUE THREAD

**Issue by stepheneb** [luin/medis#71]
For about three months a year ago you had the whole app checked into the repository. Some of the frameworks were very large binary files (aprox 100MB)

Medis.app was checked in from:

```
commit f2d4b414d08cd78b3196240c0be8f44f0a9b95fd
Author: Zihua Li <i@zihua.li>
Date:   Fri Nov 27 23:37:28 2015 +0800

    Init deploy
```

through:
```
commit 3290c1f24a3db699b82715e4fc8aaa361bae305d
Author: luin <i@zihua.li>
Date:   Mon Feb 1 12:09:58 2016 +0800

    docs(README): add commitizen badge

 1 file changed, 1 insertion(+)
```
It would be nice if you could remove this directory from the repo.

The second answer in this StackOverflow post seems like a good answer to doing this: http://stackoverflow.com/questions/10067848/remove-folder-and-its-contents-from-git-githubs-history

But if you have lots of collaborators I realize this may be too much trouble because deleting history like this is like a forced rebase.  When I have done this (very rarely) I've had my collaborators reclone the repo.

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
