### ISSUE TITLE
[Feature request] Adding support for redis proxy like twemproxy / dynomite

### ISSUE THREAD

**Issue by tuananh** [luin/medis#78]
ioredis can work with twemproxy / dynomite. Maybe we can add twemproxy / dynomite support for Medis as well?

Is there any issue?

**Comment by luin** [comment]
Any special config fields should be added to Medis connection panel in order to connect to twemproxy/dynomite?

**Comment by tuananh** [comment]
According to my experience, I have to set `enableReadyCheck` to false in order to use ioredis with twemproxy. Can't speak for dynomite though; probably same since it's a fork.

Here are the list of redis commands that twemproxy supports https://github.com/twitter/twemproxy/blob/master/notes/redis.md

However, there are commands that are not supported by twemproxy / dynomite so I'm not sure what Medis use internally for its functionalities.

**Comment by luin** [comment]
Hmm...Medis uses the SCAN command for scaning key list which seems hasn't been supported yet.

**Comment by tuananh** [comment]
I see.

I want to use it for personal use and can live without the key scan (it's the key listing on the left right?). Can you point me to where that I have to edit it to make it works?

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
