### ISSUE TITLE
Why Medis can not use a default SSH key in SSH tunnel

### ISSUE THREAD

**Issue by shiny** [luin/medis#8]
I have a default key file in ~/.ssh/id_rsa, must set the key in Medis.
How about try the default SSH key, is that a good idea?

**Comment by luin** [comment]
That's definitely a good idea!

**Comment by ottonet** [comment]
Yep, please add! Next to that I find it impossible to browse to ~/.ssh/id_rsa from the finder window medis shows when you click on the key symbol, as hidden folders are not shown. You might want to default to ~/.ssh when clicking on the key symbol...

**Comment by luin** [comment]
There are two ways to browse to ~/.ssh/id_rsa in the finder window before medis's supporting the default ssh key path:
1. `Command` + `Shift` + '.' to show the hidden files.
2. `Command` + `Shift` + 'G` and enter `~/.ssh`

**Comment by alexbeletsky** [comment]
@luin thanks a lot, that's exactly what I need. I +1 for @shiny default key idea!

**Comment by ctf0** [comment]
@luin i did just that and was able to select the file however
```js
SSH Error: Cannot parse privateKey: Unsupported key format
```

**Comment by luin** [comment]
Did you select a public key or a  private key?
Get Outlook for iOS




On Sun, Oct 30, 2016 at 4:13 AM +0800, "Muah" <notifications@github.com> wrote:












@luin i did just that and was able to select the file however

SSH Error: Cannot parse privateKey: Unsupported key format

**Comment by ctf0** [comment]
both gives error

**Comment by ctf0** [comment]
@luin any news ?

**Comment by luin** [comment]
@ctf0 Sorry for the late response. Could you please generate a new private key in the same format and post it here so I can debug locally?

**Comment by ctf0** [comment]
just follow this steps to create an Ed25519 key https://blog.g3rt.nl/upgrade-your-ssh-keys.html

**Comment by luin** [comment]
@ctf0 It turns out ed25519 hasn't been supported by the upstream modules: https://github.com/mscdex/ssh2/issues/352. I'm going to support ECDSA format first and would like to look into the support for Ed25519 key.

**Comment by ctf0** [comment]
can u give any time frame for that ?

**Comment by pehbehbeh** [comment]
SSH Tunnel feature is basically unusable...

I get `SSH Error: Cannot parse privateKey: Unsupported key format` for all keys I tested...

**Comment by luin** [comment]
@pehbehbeh Are you using private keys or public keys? Private keys are required for SSH Tunnel.

**Comment by pehbehbeh** [comment]
I used private keys and tried rsa and ed25519.

**Comment by luin** [comment]
@pehbehbeh My apologies. Ed25519 hasn't been supported yet as mentioned above.

**Comment by pehbehbeh** [comment]
I also get the error with "standard" RSA key.

`SSH Error: Cannot parse privateKey: Unsupported key format`.

**Comment by pehbehbeh** [comment]
How do you generate a working key? Maybe I can test that on my machine.

**Comment by luin** [comment]
@pehbehbeh https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#generating-a-new-ssh-key.

**Comment by pehbehbeh** [comment]
That's how I always generate SSH keys. Does not work for me... 😐

**Comment by luin** [comment]
@pehbehbeh Could you send me a private key you generated so I can test it.

**Comment by katamaran1993** [comment]
Hi all, because need to use Pro tools like FastoRedis which support password/keys and ssh tunnels into visible network from remote server.
![ssh](https://user-images.githubusercontent.com/32155934/33237401-26ec346e-d284-11e7-8f8d-466d74f92252.png)

**Comment by intrepidws** [comment]
@luin After upgrading to Mojave, I'm not experiencing the same problems as everyone else here. I cannot get any SSH key to work. I generated the SSH key using the GitHub link that you provided and that still won't work. Any ideas?

**Comment by chinaliuhan** [comment]
I am also waiting for a solution.

**Comment by chinaliuhan** [comment]
I am also waiting for a solution too

**Comment by intrepidws** [comment]
OK so I was able to solve this. From my (limited) understanding, Mojave uses a different SSH key format by default (RFC4716) but you have to use the PEM type for it to work with Medis.

To generate a new key with this, run:
`ssh-keygen -m PEM -t rsa -b 4096 -C "your@email.com"`

Or to convert an existing key, run:
`ssh-keygen -p -m PEM -f ~/.ssh/id_rsa`

Hope this helps!

**Comment by luin** [comment]
Medis 2 already supports providing an SSH config file: https://docs.getmedis.com/settings/custom-ssh-config so closing. Free free to create a new issue if there are anything else we can improve!
