### ISSUE TITLE
Looking for a faster way to delete items

### ISSUE THREAD

**Issue by rankun203** [luin/medis#80]
The *_pain point_ is we have some test keys in redis and we wanted to quickly delete some of them.

I find Medis to be easy to use, and pressed `delete` key, a confirmation pops up, like this:

![medis-confimation](https://cloud.githubusercontent.com/assets/2988555/25477703/040179b0-2b71-11e7-9b32-174bd4edad49.png)

I have to navigate to `Delete` button and hit Return to confirm the deletion. Can this operation be faster? Something like press `Shift + Delete` to delete it without confirmation.

**Comment by icewind** [comment]
It would be nice to have "multi-select" so we can select multiple keys and hit del once

**Comment by stanislasdrg** [comment]
Multi-select would definitely improve the usability.

**Comment by knoxcard** [comment]
I would love that, simple ctrl + click and shift + click for individual and group selections.  Deleting by key ID is way difficult especially when the keys are super long.

**Comment by denizdogan** [comment]
Any news on this? Medis is by far the best Redis GUI I've found so far, but it's severely lacking this feature.

**Comment by luin** [comment]
Supported in Medis v2. Sorry for the late response! On Medis v2, you can select multiple keys and hit del once.
