### ISSUE TITLE
Why I can not see the ssh key input area?

### ISSUE THREAD

**Issue by smoothdvd** [luin/medis#83]
<img width="450" alt="2017-05-14 8 52 37" src="https://cloud.githubusercontent.com/assets/22420/26033948/67d1a75c-38e7-11e7-932f-48587763d2fc.png">

**Comment by luin** [comment]
Click the "key" button laying on the right side of the "SSH Password" text input.

**Comment by smoothdvd** [comment]
@luin I already tried, but no any response. My Electron version is 1.6.7 and build from git master repo, running on macOS 10.2.5 beta.

**Comment by luin** [comment]
Could you please pull the latest changes from git and try again? The latest code uses electron 1.4.15.

**Comment by smoothdvd** [comment]
@luin It's working now, maybe I stayed in *mas branch before.
