### ISSUE TITLE
和#74情况一样但是编译报babel的问题

### ISSUE THREAD

**Issue by webkong** [luin/medis#86]
用4.8.2编译的

如图：

![qq20170601-113601](https://cloud.githubusercontent.com/assets/10398591/26663728/4e655472-46bf-11e7-8f37-932f02d73d82.png)
![qq20170601-113923](https://cloud.githubusercontent.com/assets/10398591/26663731/5077a7ce-46bf-11e7-9791-bb1bc1e6e14a.png)

**Comment by luin** [comment]
和 /Users/wangsw/www/node/.babelrc.presets 有关似乎，根据错误本地调试一下试试吧

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
