### ISSUE TITLE
 Content indent not correct 

### ISSUE THREAD

**Issue by zhengying** [luin/medis#89]
iMac (21.5-inch, Mid 2010)
OSX 10.11.6
![screen shot 2017-06-19 at 1 51 43 pm](https://user-images.githubusercontent.com/1042545/27271261-56cccd9e-54f6-11e7-9cec-e2b45e52541b.png)

**Comment by luin** [comment]
Which Medis version are you using?

**Comment by zhengying** [comment]
v0.5.0

The problem may occurs when switch to terminal tab then back to content tab.

**Comment by luin** [comment]
This issue has been fixed with v1.0.0. Sorry for the late response.
