### ISSUE TITLE
Can't See the key list

### ISSUE THREAD

**Issue by shiny** [luin/medis#9]
No matter use * or prefix:*
I'm sure that key exists

![1](https://cloud.githubusercontent.com/assets/117487/12294312/5c3abd9e-ba34-11e5-8e3a-50b40008acef.jpg)
![2](https://cloud.githubusercontent.com/assets/117487/12294313/5ca6b95e-ba34-11e5-9e99-3ba40f70c5d3.jpg)

**Comment by shiny** [comment]
Duplicated issue.
Relate to https://github.com/luin/medis/issues/3

**Comment by luin** [comment]
Just updated the readme. BTW, did you see the alert window noticing that Medis only supports Redis >= 2.8? Should be fixed in 3a0c1a5

**Comment by shiny** [comment]
@luin No alert in Medis version 0.2.0.
