### ISSUE TITLE
能不能增加类似 redis client desktop 那样按目录分类的显示方式，不然多了感觉有点乱，看着累

### ISSUE THREAD

**Issue by iiinsomnia** [luin/medis#90]

**Comment by yuqiang-yuan** [comment]
原来这个产品是国人的作品啊，我还跑到 twitter 上说了几句自己都看不懂的英语。同意楼上的同学，分组折叠和多选 Key 批量操作是非常需要的。我是在  App Store 上买的，希望能够很快出来新的版本！

**Comment by IIInsomnia** [comment]
我也是在 App Store 上买的，支持作者

**Comment by qiulang** [comment]
我也是在app store买的。发现不能想rdm那样分类就琢磨这pattern要怎么用，但好像pattern不是正则，没搞清要怎么用

**Comment by luin** [comment]
已经在 [Medis 2](https://getmedis.com/) 加入了，感谢大家的支持。如果有任何问题欢迎随时联系！
