### ISSUE TITLE
ERROR in Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (57)

### ISSUE THREAD

**Issue by smoothdvd** [luin/medis#93]
Latest master branch, yarn run build, then

ERROR in Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
 @ ./client/styles/global.scss 4:14-119

**Comment by smoothdvd** [comment]
Remove the node_modules folder and reinstall solved this problem.

**Comment by MaxSvargal** [comment]
I think the sass is not needed for this project. A very huge compile-stage library for three files? =/
