### ISSUE TITLE
[Feature Request] Order for the keys on the left

### ISSUE THREAD

**Issue by doplumi** [luin/medis#94]
Any way the keys on the left can be ordered lexicographically?

**Comment by luin** [comment]
Redis doesn't provide an API for this, so Medis can only sort the keys on the client side, which is difficult and inefficient since there may be millions of keys in a Redis database.

**Comment by jdegger** [comment]
Would it be an option to manually turn it on for smaller dbs? The ones I manage don't have that many keys but it looks a bit 'messy' without ordering.

Another idea for ordering would be grouping by semicolon, so when two or more keys start with `blaat:` you group the in a collapsible group.

If you're concerned about the performance hit something like that would take just make it a toggle :)

**Comment by a-komarev** [comment]
It would be great to have grouping by `word:` as @jdegger said.

**Comment by luin** [comment]
Key grouping is supported in Medis 2 so closing this. Sorry for the late reply!
