### ISSUE TITLE
json字符串里的长数字四舍五入的问题

### ISSUE THREAD

**Issue by wangtlover** [luin/medis#96]
存储的json字符串，如果有某项的数字位数大于16位，16位之后的数字在json视图下就会四舍五入，然后全部显示0
![image](https://user-images.githubusercontent.com/21256140/28743229-4a01e8c4-7477-11e7-8ca8-064a6d7ba6d6.png)

**Comment by luin** [comment]
Fixed in [Medis 2](https://getmedis.com/). Feel free to upgrade and try it out. Thanks for using Medis!
